# Medical RAG — 200-Question vLLM Evaluation

This notebook evaluates a **200-question medical RAG benchmark**.

## Experimental Pipeline

```text
200 Questions
    ↓
MedCPT Query Encoder
    ↓
MedQuAD FAISS Vector Store
    ↓
Top-5 Retrieved Chunks
    ↓
Qwen3-8B-AWQ via vLLM
    ↓
Save Responses + Retrieval + Latency
    ↓
Unload Generator
    ↓
Qwen3-14B-AWQ Judge
    ↓
Evaluation Metrics
    ↓
Tables + Graphs + CSV/Excel/JSONL
```

## Evaluation Metrics

* **Groundedness:** Support from retrieved evidence.
* **Relevance:** Directness and relevance to the question.
* **Factuality:** Medical correctness of the response.
* **Medical Safety:** Safety and appropriateness of medical guidance.
* **Professionalism:** Clarity, tone, structure, and suitability for medical communication.
* **Abstention:** Correct decision to answer or abstain when information is insufficient.
* **Latency:** Retrieval + generation time per question.
* **Token Usage:** Input and output token consumption.

## Dependencies

In [ ]:
import sys
import subprocess

packages = [
    "vllm",
    "transformers",
    "sentencepiece",
    "faiss-cpu",
    "pandas",
    "openpyxl",
    "matplotlib",
    "tqdm",
]

subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-q", "-U", *packages]
)
print("Dependencies installed.")

Dependencies installed.

In [ ]:
import torch
import importlib.util
import importlib.metadata

print("Torch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("TorchAudio module:", importlib.util.find_spec("torchaudio"))

try:
    print("TorchAudio metadata:", importlib.metadata.version("torchaudio"))
except importlib.metadata.PackageNotFoundError:
    print("TorchAudio: not installed")

Torch: 2.13.0+cu130
CUDA: 13.0
TorchAudio module: ModuleSpec(name='torchaudio', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7b88fd4288f0>, origin='/usr/local/lib/python3.13/dist-packages/torchaudio/__init__.py', submodule_search_locations=['/usr/local/lib/python3.13/dist-packages/torchaudio'])
TorchAudio metadata: 2.11.0+cu128

## Imports and reproducibility

In [ ]:
import os
import re
import io
import gc
import json
import math
import time
import pickle
import base64
import statistics
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import faiss

from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModel

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if not torch.cuda.is_available():
    raise RuntimeError(
        "A CUDA GPU is required. In Colab choose Runtim.Change runtime type → GPU."
    )

print("GPU:", torch.cuda.get_device_name(0))
print(
    "GPU memory:",
    round(torch.cuda.get_device_properties(0).total_memory / (1024**3), 2),
    "GB",
)

PyTorch: 2.13.0+cu130
CUDA available: True
GPU: NVIDIA L4
GPU memory: 22.03 GB

## Mount Google Drive and configure paths

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

# Existing vector store from your earlier notebook.
VECTOR_STORE_DIR = Path("/content/drive/MyDrive/vector store")
INDEX_PATH = VECTOR_STORE_DIR / "medquad_medcpt.faiss"
METADATA_PATH = VECTOR_STORE_DIR / "medquad_metadata.pkl"
VECTOR_CONFIG_PATH = VECTOR_STORE_DIR / "medquad_vectorstore_config.json"

# Everything produced by this evaluation is saved here.
OUTPUT_DIR = Path("/content/drive/MyDrive/medical_rag_evaluation_200q")
GRAPH_DIR = OUTPUT_DIR / "graphs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
GRAPH_DIR.mkdir(parents=True, exist_ok=True)

BENCHMARK_DRIVE_PATH = Path(
    "medical_rag_200_question_benchmark.xlsx"
)

RETRIEVAL_JSONL = OUTPUT_DIR / "retrieval_results.jsonl"
GENERATION_JSONL = OUTPUT_DIR / "qwen3_8b_generation_results.jsonl"
GENERATION_CSV = OUTPUT_DIR / "qwen3_8b_generation_results.csv"

JUDGE_JSONL = OUTPUT_DIR / "qwen3_14b_judge_results_with_professionalism.jsonl"
FINAL_CSV = OUTPUT_DIR / "medical_rag_evaluation_results.csv"
FINAL_XLSX = OUTPUT_DIR / "medical_rag_evaluation_results.xlsx"

print("Output directory:", OUTPUT_DIR)

Mounted at /content/drive
Output directory: /content/drive/MyDrive/medical_rag_evaluation_200q


##  200-question benchmark

In [ ]:
EMBEDDED_BENCHMARK_B64 = (
    "UEsDBBQAAAAIANqcMF02j50g9QAAAEACAAAPAAAAeGwvd29ya2Jvb2sueG1stdJBboMwEAXQq1izL8aASI1CIkXddJuewJhxsGBsZJuW3r5qWoWoq26yG/3F15P+7I8rTewdQ7TetSCyHBg67XvrLi0syTw9w/GwX5sPH8bO+5GtNLnYrC0MKc0N51EPSCpmfka30mR8IJVi5sOFxzmg6uOAmGjiRZ7XnJR18N13TePtYk4RtnBCpwdSYQR2jV/7FgSw0Ni+hXNuNNa16LTQZSWlgF9M+A/GG2M1vni9ELr0owk4qWS9i4OdIzD+l3NeumD1naW4WcSuLHcFCiVRVGVfP9zythCp8HmHKTeMMrWSO6mF7qpOmgdg+DYZ377h8AVQSwMEFAAAAAgA2pwwXax4SEmIAgAAQRwAAA0AAAB4bC9zdHlsZXMueG1s5VlLc6MwDP4rHt834Dzabqa0kyXxzF56aQ97JWCIZ4TNGCdL+ut3MARoO9nmSV65WFasT5IlYZAfn7MY0IKplEvhYNKxMWLClwEXkYPnOvzxgJ+fHrNhqpfAXmeMaZTFINJh5uCZ1snQslJ/xmIv7ciEiSyGUKrY02lHqshKE8W8IM3FYrC6tn1nxR4XOEcMpdAp8uVcaAf3K5ZR9o4WHjiYEIysnCG8mBUs11PAtTR8q5ZYjdNi/RcAX4JUSEVTB9PydyjonQHu9rWtJFKjhANUuzkodpMD5GPiac2UoBwAlfTbMmEOFlKwCrFc/K1QpLwl6Q62lksl8KCwK3KbHtu07w7cFV5D/kD49J6O6BHxxz8nI2r/H78kTKSmUgVMVbHq4ppZRL2mrWq1yRMG8JqX4Z+wkiZGOguRmMc01r8DB9sY5VmxIjlASRZQ5aRAb0KuVDTQe71d4bOw1rM9AGkAeEkCy5d5PGWKmieL+dtwqRTNGQeoZ78MmJlvakJ3nQ9HNoHciglmPgIeiZjVyeutGOiv8pI3lhVQRYJm4fmbPZOKv0uh8+e0z4RmCl+TKwumNPf3cm5dkbVY5+RWTGityMj1FBm5siJbexqfYXq18w5wQ0dPnUpaJhebR/t6cQmlftj4tOvZAb3oXW6WrfPiYmPRP9EHSPdWTNjmiQEs1PtFkJx++67OhONEsHf6JkA7JuxyZJ7PBh7m3X4ff1qsp3ZMaDshyIUmxLmeT2teN8rucqOxbBrNnzrXFR/ldx0Ofsmtho/942af2oAFWaNFbWCCYus+3LQ0b2A2b+5PP10ejCfu5JvLA6vSvzJjd3WU9txxe+oexvfj0WbqijE1RH0Z+PQPUEsDBBQAAAAIANqcMF36XAFZAwMAANoNAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbL1X23KbMBT8FUbvDTdz84RkEsduH9Jpp8kPyCBAjRAeSY6dv+8gbgKM4zR27AdLYs/ZReewwte3+5xor4hxXNAQmFcG0BCNihjTNARbkXzzwe3NNZyLDOVIozBHIVhkUHz//Qy0fU4on8MQZEJs5rrOowzlkF8VG0T3OUkKlkPBrwqW6jGDO0zTnOiWYbh6DjEFbd4lQTmigpcLEWFP0QGy8lr8YpY//I0vCNNeIQnBDtO42D2jvQAagVwsCAuBIT9A02+u9TaKiIlgJXAlP01gHRG/WDKQpes20lha/szsGCSCiDFw6ZffLqNEwChCtJajgk3HNXyrASuoangge+CZ9iBAYbDHDIF7b836ARJVDWfjG10FywenHyBR1dAZBdwZ1n1g9wMkqhq6o4DZ8s6zlv0AicoIpi9juOv5vtvAW0xSkB8H8YHrGt5Dg+9gutJqVQIqeo33K0lwhGTf5fBvwVYFFbLKUGCqibcNSmBUNigkeM2w9ojTTEgeOEfwHUDEjwL0AWeO6bsCjlAfIW3pOgZd3Qy5NbmYfCQTTMiTeCPokUtxvCA4XmFC5ERGtaXYZAvCGsIeMGWwG/M6Vcq1TcFDYIDJXNJBMBXVmus1Tz2ck23+s4jrpjdbO4BzDkV3wXAUn2gZ5CzlqoYSd7IOz57Q0dENddgn6pB3crIQ3/ywkOCoEF0pD8FUg+Up4cxqu+URJCguC1Yn6JX1LCUOZlN3ZH12a08oMc9gjJq8xpSSqWbruvAMRVakeP5hJUEwIaTcqksUWR/bAaH9mbYr+b3m7v7LLDaMiwfIswonL7XnK1VoAsP5Ahqr3JnL0ejDPURJgiIxsdJNH7mosxy8/Fl0OSm2ArGnLN5pa7Jlf2AcAsczHQNoMeaiKYAWY9a1z/j9oluHZJPB2sl7D22Fl+OWUxEr5Qyl9+e14nW6Ostx9X7UwLWm7NabfhIvcD4Gyrmk+Efgf9RTK6s897Gp6lDlTRqtPSHPvpDRdl35dYY6bNnSY5vXMTkb/IFqVm7+AVBLAwQUAAAACADanDBdDR656GUAAABzAAAAFAAAAHhsL3NoYXJlZFN0cmluZ3MueG1sBcFRCsMgDADQq0j+Z9w+xpDankXatAomFpMNj7/3lm1ycz8aWrskePoAjmTvR5UrwdfOxwe2dZlR1dzkJhpngmJ2R0TdC3FW32+Sye3sg7Op7+NCvQflQwuRccNXCG/kXAUcrn9QSwMEFAAAAAgA2pwwXRejyHEHewAAxysDABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWy8vd2S40aWrfkqMN1Ut02klPwnW6f6mEpSpbKzgr8qq7G5Q4BOEp0gwAbAiKSuzjvMG86TjG13AMTPWg6CwSqz06eUK2PDQWasDYf753v/r//97Rg4rypO/Cj883e97z9+56jQi7Z+uP/zd+d092H63f/+z//17T/eovhrclAqdb4dgzD5j29//u6Qpqf/+OGHxDuoo5t8H51U+O0Y7KL46KbJ91G8/yE5xcrd6rBj8EP/48fxD0fXD7+TC2r1r/qHl7GzVTv3HKTr6O035e8P6Z+/642+c36QH/SiIMn+1zn6cpPfOUf3m/7fN3+bHv78Xa//nXPwt1sV/vm7j9853jlJo+M/sr+7XsaE97PwfhHe/9ghfJCFD67h0w7hwyx8eN/ooyx8dP3svQ7h4yx8fA0fdAifZOGTa/i4Q/g0C58W4YMuX90sC58V4aMu4b2P+e/Nx/u+PPlhc4HefZ9ffk3NBfp3XiD/5ZP/uOsC+a+f/MddF8h/AeU/7rpA/ivYu/N3sJf/Esp/3HWB/NdQ/uOuC+S/iPIfN+eAH66ZTKe+X9zUlT/E0ZsTyw/pMeQ/f+p95yTmnyj983dJGuu/ev3Pz7/IRV7NpYqf/gv56WXsH9344jyrNPY9FPkzidwoLwq319gEBf9Cgp/V1vfcwPklkkyPIn8lkb/4u53vnYP0gqL+Sj9mdDylzt9UuE8PKPATCfwpTN5U7L74gY9H/I0E/vrtpLxUbZ2/qIP76kcxCv5MgldnlaR+BL+Y/yIx/4jirfNzdA5TFPWFRH2Ko3O4VdtQJYmz8aJYoei/kei1CtSrG3qKhz6T0L+6Xnp25VvlsXP2q+fulC1uwf4xX5JUhfLFOj9Hcaw8+FUtmbHC0zl1fo++qhD+rq9I3OKc2gPXJPBvbqpC7+L8W/LvKGzDfvNe3eDsplHszKNUVUf8QWeSUkLplxJK31xvVP8Vmf/y4ePHHswqLKT0WwVzCom7/lL86BS/WzCvkAv8Gm4jL/bDKIj20K6/skA3wQmF/PzmEMXwt+cTCcgTSQA/z2/WKCcKg4vz5qcHxwtc/5g4yfl0imJJLy8XJ5b8q17V1lGv/laFnvoeJhsyxj8Obuq4sXLSg3K86HiMQie5HE9pdEycaOekl5Ny+s7Wd19UqpL/DZNS5dpm6r77z89//bfP/T9/993Td989/e3X+b/9vv78/G+f+//+7x/kT5u//2Xz++ff//77r8VfPH3nyA//+7//Xz39K78zdziDGS0bcpo/eHWiQuIzEudIXCBxicQVEtdI3FTEhgEHJQMObAbsQwMO7jTg4L0GJBdYq+Tkx5J9sP0GHe036Gq/wV32G/wL7Dew2K/wm/jQeDC4OG6SRJ7vyjh6dDdJD0cXG3DADDhoGHDADDhgBpxAAw6QAZH4jMQ5EhdIXCJxhcQ1EjcDqwGHJQMObQYcQAMO7zTg8L0GJBf4RclaCX/+DTsacNjVgMO7DDj8FxhweMPz75yc3cBJ/H2YOG64rTwIT0kU+27ik0fgkDlw2HDgkDlw2O0ROEQOROIzEudIXCBxicQVEtdI3AytDhyVHDiyOXAIHTi604Gj9zqQXGCuzjH336ij/0Zd/Te6y3+jf4H/Rrc8AD03dCLPO8eOHzpLN/7qh0kU/ilxtn6i3ERh742Y90YN742Y90bdnn4j5D0kPiNxjsQFEpdIXCFxjcTNyOq9ccl7Y5v3RtB74zu9N36v98gFfnbjrc/NN+5ovnFX843vMt/4X2C+ccvDD7z4HZQbp87O9YNzTHw3Zr4bN3w3Zr4bd/PdGPkOic9InCNxgcQlEldIXCNxM7b6blLy3cTmuzH03eRO303e6zs2sJukcaTCVFkefZOO7pt0dd/kLvdN/gXum3R33958pUl0Orh75QZOrHbB+Zv9OThhfpw0/DhhfpwwP06hHyfIj0h8RuIciQskLpG4QuIaiZuJ1Y/Tkh+nNj/CpPSX6Z1+nL7Xj+QCvynrS+C0oxOnXZ04vcuJ03+BE6f3LYL6cRR+2Kqd7/l6Td4N1dEnSzFTZsJpw4RTZsJpNxNOkQmR+IzEORIXSFwicYXENRI3U6sJZyUTzmwmhF/CX2Z3mnD2XhOSC3wOd8pL/eicOL+YpA3NOOtoxllXM87uMuPsX2DGWecl0USp0Izrh7vgrMI/iAlnzISzhglnzISzbjPTGTIhEp+ROEfiAolLJK6QuEbiZmY1Ye9jmTH4aLMhXJT6C41p8yELvN2I7ArP58Q7B1HyVQUqdQNoQxZLfcgCuBFZRIsT7WEPsiIbpOnF9HLS7Ea0c6IkVZEbp4fYT9myaPXCZSf2Pjas2PvIvNj7yMwI35C+5MNW3QjVZ6jOobqA6hKqK6iuobqpqk1XVsifnsWVvY/Ylb17Xdl7tyvJFf5ueVdkMdyNvc5u7N3nxt6/wo29W9x4dC/ZWqnZHnTOsR8KkZXGrpfKE1LPP0JizB41Zq9pzB41Zq/bnkU+bM2YSH2G6hyqC6guobqC6hqqm6raNGaZoBFikxsTIzQ0ptWY74ZoendTNCxSuL7zERu0c8gnFtLmUBL290QBAzppJGsqqR/uz35ycDz3nKjkqXDZk94HTAXIC/c/Ou5r5G8ddyvou3MOr+4+Ku/ghn5yTIilyV39Fr05fuIcLqcoPVziyN/6ydHsQwYXoW72YZSorbmNt4PvHUqbJfm0OFDu1vECP/Q93w0T+Uxyx84uih0/Jf6nzE6vCe30KLXTo9hOD+4ZfMnHrSUASO5AdQ7VBVSXUF1BdQ3VTVVtJoAywSOEME8AGOGhMa0J4N0QD7tCyzYKC7O5v3PIJxbS5v4Bd7/2SjMF/Ogk6uTGbqoclaTuS+AnB7V1Yj/56uxcL43ixNnF0bEwHnH44Ia1paP731Fcu3QUO14UR/rR7capisX3esHAuP4QveXx8je7nYpVmJpbkmtWaL2Dsi8RV++yYvsmKtSjrFCPwkJ9+Jz7ko9bsz3khaA6h+oCqkuorqC6huqmqjZtX+aGhMHltsfgEI1ptf270SF2hTZ4j8XZfN855BMLafO99ft01KvY6uiG7l4dxT16ei6QgTjm5nn50PoQ9w5xFPqeE70kaXz2Uv9VOadzcDTWzmyZ3UTxRHdTJ44C5WwjJzlGX2Ve4akkcTWnLj/ihwc30DOMre/5oUqcU+BeiLsphdRrYkg9yiH1KIjUw2tf+bg1d0MWCapzqC6guoTqCqprqG6qatPdZSZJvkzubgwl0ZhWd78bS6JD37JHy4JtFu8c8omFtFl8dMejfRs5YWRehmPHzSfUvnnsus5JxUkUErfbiCXznuCc1Cn1PecceCpOSpZOY+WmkmhqC9jnRG2JdSnE1GtSTD2KMfUox4RXhr7k49asC1EmqM6huoDqEqorqK6huqmqTeuWkSY5Psiti5kmGtNq3XdTTewKdqSQRdk82znkEwtp8+y468u4+nYKXD90XqK09Korxsq8K35zT6c4cr0DMW4b7STP/Hwde6fc9BwrPXs++vvY9cPSvNtPCtHZq1DF1ddyYmXKRfWaYFSPklE9ikbhOeWXfNyalSEdBdU5VBdQXUJ1BdU1VDdVtWnlMiUlB3m5lTEmRWNarfxuUIpdoY3PZ3E2M3cO+cRC2sxMwr4odXLcILg+9ZwkdVM90U6c1FdbMfbNk2wbLXUdITrJDBk8Xs2T3ctd/HZQoXj4IDcVR+FexeWn84tEh4m/VTG1M8Wqek2uqkfBqt6k60oZZKug+gzVOVQXUF1CdQXVNVQ3VbVp5zJkJT/E7YwpKxrTaud3c1bsCnN1OtgezdPubu4c8omFtLnZ+nXm+1fuS3ROyap46XU6e5FucbaNvhLyXw9TvEZ/9behqq2FvQFQK58MqMT4P42cJJBnd5o4pzjaxyqRwjXE3BTX6jV5rR4FtnrTrm/MkNmC6jNU51BdQHUJ1RVU11DdVNWmucvwlpS84ObG9BaNaTX3u/ktdoX1QZ3tD+tZd3t3DvnEQtrsPeMzb7b5lS9RFXNis8ZcPHP3kRuw1e/ZfWRlnH3JsquWkyQlq/uJDjyd41Mkr/m7/B4/HKOtv7vIcllxf8ThlAXrNWGwHqXBehQHw7PPL/m4NYdDIgyqc6guoLqE6gqqa6huqmqzVEQZDJNyVNzhGAyjMa3VIt4NhrEr/CM6Kjlc9ptyA1wY5lcWavF495BPLKStbMTHziti2lpmF9usfbmB/0e+uuwGjrt99WkFiZshsfrRdRVuo6Pciyy9Vd6u/bT0Xq1M7RK1NZvu4ms2Ka/eS6XkRJMr61OurE+5Mryy+yUft+pqqD5DdQ7VBVSXUF1BdQ3VTVVturoMlvVtYFkfg2U0ptXV7wbL2BUWoWcpANPr7ufOIZ9YSJufGcVmMBMn8WKlQnnmiT/0LnLpRVs7DTheMgExtI0zEx/Hyov2oU4QYM86iKSIkhvI3N1TccXX11vN5+RblSrB0lJHuXFANrCqd1SxdZNK61Mqrd/rOB3Px63ZGmJpUJ1DdQHVJVRXUF1DdVNVm7auFHayYWl4u/4vNKbV1u+v7dS/i0phYb+58RbbujuRxkLabM2qSF3C9KAS/w/lHM9B6p+C69T8wxUtO0V+bm95F/fDNI62Z69OoKWHWCWHKNgmjiAmSibbKtzqjWQyaaffWfQmG2eHy0nFqQrl7fnJOfj7g+MdokAleg/xKd+vNr7PC0TJcloa+y/nVL9eePpf7dUVAt815EuZZTPIirxyZJlFlgFy+u1FOXqW79NJAK87BQpP8cpT/Y4wSz5uLVvg6lO4/BSuP4ULUOEKVLgEFa5BZWfY+mWGrW9j2PqYYaMxrdni3Qwbu8INpeAGXRNGd4iNhbQljMH97+5XEPU6iTbEi5uqfRT76ppKMo5VfUtVHMpemOulLFUMrKlCV4nrmRGrBeMyYi1bIfRjR34j4kC/uZ/i6CVQRx1mSu9cbzdf1SPOpxhbv4mx9SnG1h90nSdAjA2qz1CdQ3UB1SVUV1BdQ3VTVZvOL2NsfRvG1scYG41pdf67Mbb+nRgbi+O+7w6xsZA239shtmwJ7eTGfhKF4ihEvJiX++hVxdmLtf+HngMQX1uQNnkWm6Jz2qE/L5a/iGW3Z085iX/09QP9+m3Xdgf0+l2xkpg/0w8qOFXyVnpQR+JxCrP1mzBbn8Js/WHHhbt83JrHIcwG1TlUF1BdQnUF1TVUN1W16fEyzNa3wWx9DLPRmFaPvxtmY1ewEzEsiju8O8PGQtocPup8OEUlXuy/qIL89lRSYG05iOK4TnJSnr/zPefkpr4KU2L3kf0xHrthItGOrzs2CGqTpq73"
    "1VTDS+Poa34jucmFWVdOcpay5k6Y/bv43nU9MFvGc86Sj1L64k/xt34Tf+tT/K0/6mp2iL9B9Rmqc6guoLqE6gqqa6huqmrT7GX8rW/D3/oYf6MxrWZ/N/5Gh76FXGXB3PPdGTgW0uZ5CwNXdrp5tGseZesbuOXt4AdK1vj0dFmm7ZWH/tFNVey7AfH62Or1n+PoUKqsZybhwrG6Glz3okD24qrTd+fkxmnpoMlezsW9quzEqT6g4u7k2GlGrmdT/mzfTz5g4HtmRYKkAYrO9ZvoXJ+ic32KzuE32C/5uLU0ANE5qM6huoDqEqorqK6huqmqzTRQRuf6NnSuj9E5GtOaBt6NzrEr3LJZN+maBLqzcyykLQlYv1BNz2XEDZzWaz95gV45vx5XK56xep++Yi+SEm6tRKYr4ErR21gpL3CPp8R3r098eTEwLyNZppKluq0rbJ2Uu5HdAY3vHqP0INh9uHVe3Bf25Kd4Xb+J1/UpXtfneB0umpSPW7M8xOugOofqAqpLqK6guobqpqo2LV/G66TTDLc8xutoTKvl343XsSvcWEKJhXPbd4fsWEib7UnYQlczkr07M+c++ppRqxN2p1i9Zi1LjspN9Jt0paJES8uHqf3QuZJ3BXnI/yW/izSVk2n61f2g82y+RmdW5nM0r6gtYZC9686f/ND1L19U/gnoCj7F7/pN/K5P8bv+tKv5IX4H1WeozqG6gOoSqiuorqG6qapN85fxu74Nv+tj/I7GtJr/3fgdu4J9G3/W1fLdwTsW0mb52b1HXqrb+9ejavlyvazp6UmCOSQap64fpmxr38bjZVTddUXBeVHpm9RWc7O9/NK96EoSmhoqn8ARtTohkP/3EkqvxqAUHavkHKROrP7n7MfK2Z1jPSXICmqQpECJvX6T2OtTYq9PiT28mP0lH7eWFCCxB9U5VBdQXUJ1BdU1VDdVtdlbpkzsDWzEXh8TezSmtb3Mu4k9doVlcvEOvpuy/jIfO6YFFmBJCyykrcdMG6sHdv5NSZfyIbUrvZenB50tHD/c+q/+9szWAtjooNbiwZWXeRXLGr2nT8XpmhVbddIg/asuMBHF2xrw46flZX05hiPvJFG8NTWpEinE9SFV8dFJXP2bQxrZUK5v0OT6BpTrG3Cuj3SzgVwfVJ+hOofqAqpLqK6guobqpqo2vV/m+gY2rm+AuT4a0+r9d3N97ApLtRXnk16Tv7Iw7v3uXB8LafO+9ct0tupVBdFJtr2FwK2erLmuCgCEt8z/uHvleOc02u3Iyz+7i/rLf/lErHtOpR6VbC6k8flYs7456n45mZ/NbkXoo+s2vhSpe5HGOuwNoHpXFcM3ib8BJf4GvY5vAPm4NcND4g+qc6guoLqE6gqqa6huqmrT8GXib0C4rvWvf6O9HGmMzas/s6hymvjRNL90ft3l9bOx7e8uR0cjaVu5zm0dWUSb8e2NHfWRuW+ydP4/WctXZ+sLUxtc8n38cxirQO+f5ev0ans2a3zE5RSfDEuMnj5o54deLJcUssCPE3J+pnrBikGbkN2AQnYDCtnh06/5sDV/QsYOqnOoLqC6hOoKqmuobqpq05+VTo8Dmz9Jq8fBXf4cPM6f9/Z87Nz0sXvXxzvbPrIvRya5rrOLPM2uu8as+Vv41ZHXp9xWpa7PjsaxYT7L/p5Sf+gpfO1snH722vo98oaPoOMjb/nYtecjbvqIuz7ito+47yNu/Ig7P+LWj7j3ox1/G5Txt8HQZkqMv9EYuymHjzPl8C5YnoVxT3ZuBMki2jzJBkrdS+HIKC/bph+b5tmY+qFedCYeJJf9nBiu/SWIIr3cnsgiuymr6B7lP7Q7k6wblrW0YnWMiiebvNqA8mqDYccKTvm4NVNCXg2qc6guoLqE6gqqa6huqmrTlGVebTCymRLzajTGbsrR40w5uq/4C4vjruzcHpJFtLnS3iCyakZ9XsVy6oxdTGaoyvtDHd18fpp6Yj/iNgqMDZrA2IACYwMKjOHzn/mwNbNBXgyqc6guoLqE6gqqa6huqmrTbGVebDC2mQ3zYjTGbrbx48z2HmqMBXPHde4JySLaHDe2PAe9KPT8DNmqPRPPiYr/lBTvk8SBtH9m6Liev82bzRkbus7LOdabOTulAvnfDAaTkivspZFyXIMmxzWgHNdg3PVZCDkuqD5DdQ7VBVSXUF1BdQ3VTVVt2rPMcQ0mNntijovG2O05eZw9J/cQ3CyK+7Jzt0gW0eZLe79IPXHMSez8XS6vhuBHYb6s8xJH7nVJJzkfj66czCJ2nXC7FtUJjVdD+f/ZOyMFrQZN0GpAQavBpOMTE3JWUH2G6hyqC6guobqC6hqqm6ratGSZsxpMbZbEnBWNsVty+jhL3tc1koVxT3buG8ki2jx5Q+fI6hRVr+AIJnnwT8RzU8sjUnd/zBy3c1N/f2avhBRvGjTxpgHFmwbTjpaDdBNUn6E6h+oCqkuorqC6huqmqjYtV6abBjOb5TDdRGPslps9znKMCbI9A7t2hmQBFr/dRzixsL/KVLS5OJM9Bps7Gnm/quuBB+LFmcWLrOtVZs986rqVH9ubH+ZNsaojVfzaJI8GlDwazLo1xcqHrfkVgkdQnUN1AdUlVFdQXUN1U1Ubfh2WwaPhR5tfMXhEY6x+ZVF3+HX4jk6SLJb6lgVw37KIFt+ysF/0nmO+z7GTrcCrWUOl21FIb5rQTaMjWdSh144EDqg0iryW6zUW/W+9XpSk/m7HuaDq9cvOHDa5oCHlgoYd+0jmw1adCdVnqM6huoDqEqorqK6huqmqTWeWsaBhz+JM0keSxtid2XucM3t3nw5iodyYnZtKsog2Y9qbSpaaPJXfJYsdyW3s7wS8E5b4+nSNlTmrbw7oRSffI49XNrpejy0X7sv8elLBqz5n7JOnaPWCFa82kZ4hRXqGvW7EQD5szauQ6IHqHKoLqC6huoLqGqqbqtr0apnoGdqIHtJaksbYvfo4ooddqmVzkoVZSvR1D/nEQtqsSsI+78MoVo4fx+bbTZ0X1/u6z0736f8rvKw3Gz8Um432tVo6oKO+qVgvA0vlL+Wk/lEAYedNqa9PzmfJCuFXx4t2OyWoj2k/F+nZcFa++yIvr0LjH9ykYIO+d56lUZYfXpkkP/kPg/pt5WFergomp5JYEqDY0LCJDQ0pNjTktblIFoDcEFSfoTqH6gKqS6iuoLqG6qaqNrNAmRsa2rgh0l+SxtizwOO4oeGd3BCLs6WB7hW6WEhbGhh0egUunbTRB+NNsggj+RrlfJ8b2BEiNtxn5+DKwRwvCrZO4Capc4xC6QUt1Trkwa1zwl6ljiw0S7FfOWms4r2sNTvls0Da8ehA0LX+j+uk6niKYvPKft4fDOJfPvFHUgGFlYZNWGlIYaXhoGsqgLQSVJ+hOofqAqpLqK6guobqpqo2U0GZVhraaCXSc5LG2FPB42gldql2xJdF2pJB97JdLKQtGVjDTLcplaQf8pl5/mAtyvic4kjYfsfNa2FfSd1AeQLjk7TAPuLFOYdeoCoPdu1hSRiv4m4VOmlsyudHjiqO+/oqlrwgpTnlllF7HV13MCs7lF+b+J4CUcMmEDWkQNSQAlG4JvWXfNya7yEQBdU5VBdQXUJ1BdU1VDdVten7MhA1tAFRpBsljbH7/nFA1PBOIIrF2VzfvZQXC2lz/chGaGjwxGAZb65ZgtZFNZ604b0okYezd0WIicHJGJ/Fis4x8pP0HPt/ZDU2knNoDt7qP0We58ocXZfdkymA9MTKHvpSInSv9Kki1zlK+9ms8FDWCKt6z06qTwkeonOwlcM8RZl+YntKZg2bZNaQklnDUccaPvm4NdtDNAuqc6guoLqE6gqqa6huqmrT9mU0a2hDs0gnSxpjt/3j0Kzhe9AsFmzzfveSXiykzfvWsLwFrL/fq1hX436L4kSFScZV/Zi/AJRWCwJ/p5L0Io2grS8CZODPzpsbfM3aXEvFjbyKQF53MwmkSV8if+UconOc5I/5XRSZiuEH90U6ZslRfnO7ZRSMOJ1SXsMm5TWklNeQU174GEI+bs3pkPKC6hyqC6guobqC6hqqm6radHqZ8hraKC/S6JLG2J3+OMpreBflxaJsFu9esIuFtFl80vKGn1XDrD4py0dz8+l+qYhP5m3nHAYqSZxQqa3aEqezTyqrdkdfSum6stx38BNdfDfaoZMMT87LOZWVvtJiXgGoSWLIVvbyDl3VTyOHkLLPSRIARcqGTaRsSJGy4aTrox4yZVB9huocqguoLqG6guoaqpuq2kwAZaZsaGPKSGtMGmNPAI9jytilbtmW694ks3vIJxbSlgWmLVkgO7a3/HmxKQ7OF+/12Zr/NRXsVJz6UgOh8GORC9zkK00FrDya4x6lHYiKzSqjHzpSIdA8+3XfTrmtbMovDtfP91oPPv3iIG4nDqcE27BJsA0pwTbkBbowwpaPW3M4RNigOofqAqpLqK6guobqpqo2HV5G2IY2hI30x6Qxdoc/DmFjl2ppgcvCbO7uXqqLhbS52xpm1vDl5Tja1Q8I+mGtPS06r69Sjc1YOurRj1p9YOtcog2dDZqksnXwvZNX6UdnGLNCvPIhTFSiC4jpfULidUq/DZv025DSb8NZ1+k8xN+g+gzVOVQXUF1CdQXVNVQ3VbXh9VEZfxvZ8DfSKZPGWL3Oou7wOrvUjfU4WbjF891DPrGQFs/TsO1WnFMpx6nRcXxkI5t2Y1uzMf4qr9nXopuyS6/X1d9kBSCNnK9h9KbraYlpyySrLqVZKtGZFdcKVdbEU4LdUFfbhXf0X9U7Klt71MTnRhSfG/GyWphszcetWhuqz1CdQ3UB1SVUV1BdQ3VTVZvWLvNzIxs/R9pl0hi7tR/Hz7FLWattsiCbobsX12IhbYbutb2oF8Uo8zbSurRudDqbQyD6OKU6pU9NoM4P06htjZ6N/w/cv7pRX9MPnZOKpPff2yHK3xz0Ll0+R8dP6+q4FUs3KbsRpexGvY4z83zcmqUhZgfVOVQXUF1CdQXVNVQ3VbVp6TJmN7JhdqRVJo2xW/pxmB27VPuuOoukJfNYwN+icI89fR9lRz/St6LThGPqCV7nyfqRKIVA5Cf0kY9ssU3cvq+W9JGuVVGYkFk5G12/b193zXUjuyStNL98UYaRlYV22cc3B81eBZsTR/vp9/kWfKyE3NGTej9MzoEfPjn74OxFUk5b3h2eCsDvyfTVObnp4WLQveq7h1nk+5znDllV1A0FdJsON3Vif39InTB602xf+cVCZh/ZCqCfOL+9/NST2t6pkt9A+YhZ0XGSgCjhN2oSfiNK+I0o4TfEZXrzcWsJCBJ+UJ1DdQHVJVRXUF1DdVNVmwmoTPiNbIQf6b5JY+wJ6HGEH7tUC+fLwnj2GXTNPvfBfSzsOqPIYPxS2SF0YEaa3X4wjW3lR72zfqkgOYcSfvqlwOzA5/12K1143b16KrYEzFtJvSOvnJMLgvKKgC5nJLnIPZrVhUSunOWj0oZFGm3dS7aC+Ll4TyllPmkjEL05brj3Q7cgnHRlCP2Zo+NOaoKWT/3kHc22ecejrWldru9JzuuRdEMpwlGTIhxRinBEKcIBLhSaj1tLN5AihOocqguoLqG6guoaqpuq2kw3ZYpwZKMISctPGmNPN4+jCPkN2IFiFsfzzbBrvrmPH7SH1Y+uZwuS8ln10ZxLGSm+Lj/mOcq+UMFGztcVpHyvnq5o4PfpSg8/lfgiU9xb/gX1Sqm8Lh2edBbRS0XlFqHFokbW4ER9O0Wm4lrkbM9J+r3zj+wd7DrPKmhDnQTNjWU9SvSXoU8llL6OU+BepLJimNVP990wKZilHGiOYt3PlKQaCi6OmuDiiIKLIwouDsirFQQXofoM1TlUF1BdQnUF1TVUN1W1mWrK4OLIBi6SzqM0xp5qHgcuskvZuQYWxRPNqGuiuQ9ZZGHL2I/kaO4fqpZsSt2Gr2RDKuxgdmghWw01j/ST5Qw/G/r3g5K9ilhOIITZiWCdRrb+H3/48k/15Lwp96v5r4Nyt653yBoOeVG4O+spVWMiIy3Iin4lftYg7brnGUQFCnmd1eiJlrRbOVzyfqZRqD4IErkt7kGv6GQdTfPjEmlwMQPsY1daMOQUt/+HrNTa6oNUv5VKommikiOKSo4oKjnAOy75uLVEA1FJqM6huoDqEqorqK6huqmqzURTRiVHNlSSdD2lMfZE8zhUcvQeVJIF83wz7ppv7sMk7WGoME+pw1C2KguRqrYlWTLuMltnlbcN92UbHX2ZvchB5utER6ehU5Qk/kuQVdXK5irmQITpcOYF5212kFNoya9Pjn909/rlLIr1qenEi06X751NibXKJi3NNeHi5820JZur6BXrvPtadoDzfDqpuN54leQWCmeOmnDmiMKZIwpnDsjyDIQzofoM1TlUF1BdQnUF1TVUN1W1mVvKcObIBmeSVqo0xp5bHgdnskvdwGaxUJ5ZJl0zy310Jgsj5y9zR103e/L1miuR5UXnMDH1LTMkK4ezSZIht/A5jtX+HLixvKr4AldLyog87xzraYlOMNJ3oXgJyrZ/ol2qwnyhyHlTsmr7JPilnvqkh0ssN5xnBBOaAV75vhXpCZUlnq9+KKj3ztnJX4X72umu8vEPSUOaafOTtuMe1e+hkmeaDOiIMqAjyoAOMAOaj1vLM5ABheocqguoLqG6guoaqpuq2swzZQZ0ZGNASf9WGmPPM49jQNmlbqVGunZxZQE819zHgLKwxkGv0ropXJLJ35ZuaNRMv4xSy1a9rHtd0g18obukjWS29/TmXrIsEUTh3vReq0Il2cpO+W7qO0ShG8fRm4qzXaKiC61kjvw4aPa5K/1kW46EVz9fJWk0sdIRxUpHFCvFfU6/5OPWkgbESqE6h+oCqkuorqC6huqmqjaTRhkrHdmwUtL3lcbYk8bjsFJ6Awd1tp4NZYE8Xcy6pov7oFIWVp2aZKu4WUr4cIy2/s4seB5U7J7Mom509NPKjlK+qBv4ScoyR8sX6m+dUiU2PU14jYJXpV+Dnq5l2J6c5E0FMh16ytcw6snEFG7bukd3r/QSTCCb2pfy9lCpdJU+cXbRiaP5qd0w9WNzh77nbOPzPrH0jKt+xkr2aIKqIwqqjro2iM3HrWUPCKpCdQ7VBVSXUF1BdQ3VTVVtZI9xGVQd20BV0iCWxlizB4u6I3uwS1lpNhZEMwcLoJmDBbRkDnuY8VKOjX14TT5clzdLG9GWxhvs+j8bJO26RZ1k7yL5OoesZ6a+lzzpLW3HbGlLhiggtsQ7qO05kKWSFz86JXqHqFgSSdLsP3RKKNZu6vhrKW8I2pq9qcnM42I2eVxZmPH1wketP7Us/b5c5ICLCna6nka2XeTmO1lyWs6wdzinVL+cck4ZNwnZMSVkx5SQHeAKk/m41ZwC1WeozqG6gOoSqiuorqG6qarNnFImZMc2QpY0nqUx9pzyOEJ2fF/7WRbGs0qva1a5j49lYWWWzlR/qrShLV4C4JFWV7Y99IPbcrqFjfzzwQ+2sSpGdKS0XL6X4sRuXqxGQy2+SvTibBilvlfuWa/XRJOTUt7hydFFMQNzGE7wP9khln1gvRwbq5OS9xJd+ObgvvpRjNdMHE/uLCtrVd7Uoiu3ghTqjvfVL++63kSSDWV3x012d0zZ3XGv4wZzPm4t2UB2F6pzqC6guoTqCqprqG6qajPZlNndMaE2//rTz7TpLY0pmlXjbHMTvGvvcj2+m9qlkayOLQvgdWxZRFuqIWHLor7VUW3NXojjyoKoBjLM7ObayPol3xRKY1+96tVb0/iaZBkyqN7dPUTxUeYSfuKcYl+arASXnP7VGzyyIhvIAockALOfk1G4xLkUeh03odcxhV7HFHrF52jyYWvGhcwrVOdQXUB1CdUVVNdQ3VTVpnHLzOt4YDMuZl5pTItxBw8w7n20Kwvjru3cBpdFtLl20OLa8GrWrdr5oe7VUByWUccXWSdIDnw/lo3wj65FZasXqrivyYCOKQM6pgwo"
    "eWxCBBSqz1CdQ3UB1SVUV1BdQ3VTVZvuKyOg46HNfRgBpTEt7hs+wH13wp8sjtuvc8dbFtFmP97xNjU8lifbCPLSLWxR+VU/tyV94eddbzMMMiOVqrt/pqJr4B5lvTAujpmY8yTKcf1YthaIQyk6OW6ik2OKTo67NsHNx61ZFKKTUJ1DdQHVJVRXUF1DdVNVmxYto5Pjkc2iGJ2kMS0WHT3AoqO7+ouxMO7Qzt1vWUSbQ+3db68uzI5diEH3Zz85ZO7NuhuZ90pTY02oIuLZkf04qWk+RsxHccJxEyccU5xwzHFC7D1IE0L1GapzqC6guoTqCqprqG6qatN7ZZpwPLZ5D9OENKbFe+MHeO89HCEL5g7s3A2XRbQ5kH2s7Fin+WL1UyzWvYyu81TisrHdZXvzfSXR6eDulT7IqTviWhvAVy9asV+TuBtT4m5MiTtc5jwftmY/CNxBdQ7VBVSXUF1BdQ3VTVVt2q8M3I0nNvth4I7GtNhv8gD73VUHkUVx33Xudssi2nw3sfou60P9hN4Pie8mLU83a7nBanTFYE3UbExRs3HHDrb5sDWDQdIMqnOoLqC6hOoKqmuobqpq02Bl0mw8tRkMk2Y0psVg0wcYbHpXFTIWxh3WuXcti2hz2LTt7S9bMr3y8G0vfVO7xbxDHIW+V6shQAxHMa1xE9MaU0xrPO34RIOUFlSfoTqH6gKqS6iuoLqG6qaqNg1XprTGM5vhMKVFY1oMN3uA4Wb3le5ncdxxnbvXsog2x7UX/SuttWhOqbTqWWyLWjCLmd2ApySKfTfx2QoKhZvGTbhpTOGm8azjSxxkm6D6DNU5VBdQXUJ1BdU1VDdVteG5SZltmny0eQ6zTTTG7jkW1sVz7Bo3gtQsnFqPBXDrsYgW67EwuNNQHC0tvFcmEa7bhdZ6+WzE3IslZBm7sXqBshsnTSxoQrGgycduU8582KobofoM1TlUF1BdQnUF1TVUN1W16cYyFTTpWdxI+s7SmBY39h7gxnsq5rEg7sHOvWZZRJsHe2179J4Ukb4+A1ve6Nj1rnt7R5W6SSoPPL2zJ9iODcSrXrDiuCYbM6FszISyMZjDy4etOQ6iMVCdQ3UB1SVUV1BdQ3VTVZuOK6MxExsaQ7rH0pgWxz0AjZncjcawSEuhyu4hn1hIm/NY2HX/oLJ38BaZ8nG6DkO2h8AeczYGJqPWQHNHveu+Dy6ebCnox+vhcopygdiTAjCTJgAzoQDMhAIw+OBOPmzNnhCAgeocqguoLqG6guoaqpuq2rRnGYCZ2AAY0taVxrTY8wEAzOQ+AIaF2bzZvZ8rC2nz5qCTN/PJqUCwqRCquqSAlFcP3NPJUOnxMctUxLKDuyzrmjJpjpumrvfVlEGR7931HDeWPhDEtRScmTTBmQkFZyYUnMFPkS/5uDXbQnIGqnOoLqC6hOoKqmuobqpq07ZlcmZiI2dIC1Ya02LbB5Az7Br2vQkWZXNt98arLKTNtcPb3ydLpYxycs0/noL8zJ05mKb5cdMcUQYlzmV15Ez5INcUaveFZfflXMzR93K7Xin3jDHXh2+Vrtdm2feojlhxbxOqmVCoZjLs6l4I1UD1GapzqC6guoTqCqprqG6qatO9ZahmYoNqSCNVGtPi3gdANewabdwbi7P5t3sLVRbS5t9R61NXfTsFcjjFPA6L4kClIxh5e2ViVhtOU68cmJ1uN+fU5NSZnzhyAlfOufuVujzRS5LGZ0+fKQnOUmzato1SvYmKf5tczoRyOZNRx1Lt+bg1/0IwB6pzqC6guoTqCqprqG6qatO/ZTBnYgNzSEdUGtPi3weAOZP3gDks2Gbi7r1QWUibicftU+es4q/2ahTv3dBPjh/ySbSpkR6FycE/EROPrU/c31Tge9GL66Uqdk6XIIr94s1ZylOok6SMc5AdcrX4lAI8kybAM6EAz2Tc7XBHPmzNphDggeocqguoLqG6guoaqpuq2rRpGeCZ2AAe0s6UxrTY9AEAD7tGC1/AwmwG7d7JlIW0GXTS6SlbtmPx2lnUEm92HyCWpaCPfqpea5NXsfOjbOrIcXDTRkH6pXTAFaqDVvzb5IMmlA+aTLrOkyEgBNVnqM6huoDqEqorqK6huqmqTQOXAaGJDRAi7UhpTIuBHwAIsWvcUOyOhdpM3L0RKQtpM/HURuLhE1qmRq5u92kqYbtB0aOUuLaFHTpFwcW76Bl49GoK0oRbmT3nU2Y3LUaoFpdzE31EWx7Jeq3MZwtVlDiaNImjCSWOJrzfKMYf8nFrFobIEVTnUF1AdQnVFVTXUN1U1aaFy8jRxIYckX6jNKbFwg9Ajib3loRigTYDd+81ykLaDDzrtMJcOYClj5Uoc1ZLv3JmlZesD2BWHyt6M++9MSoIZRaosvaCSaqi4q+IXSmsNGnCShMKK00orITrV+fD1twKYSWozqG6gOoSqiuorqG6qaoNt07LsNLUBiuRjqE0xu5WFtbFrewaVjyCBVmc2j3kEwtpcSoNw/PlclPBwD/6qakzKy068hpF2KFsnJYdoGvlI6ldkLUTzMvh+7LrpCuZ5DWdshJR2L7VWyjbd9qkm6aUbpp+7Pi0zcet+heqz1CdQ3UB1SVUV1BdQ3VTVZv+LeNNUxveRNqC0pgW/z4Ab2LXuBE2ZOE2J3dvDcpC2pzc6/rMzYqjJkLfkzkyu2jbxq3M0c9pua+v5hmLF9yWiqnVYStWbWJRU4pFTXm7T1xmOR+3ZlXIRUF1DtUFVJdQXUF1DdVNVW1atcxFTW1cFGn3SWNarPoALmp6NxfFImlxMhZg8+h9VBT9UJWNH1Tz4CmrT5jt4BY1VYt2mvk+b5MWJs6mFJU0pgmdlyg9OOnlpJyeqWQo/9kv99mTNauDvz9UKwk5Uh7ZkXvZ6yPhfmxKHZrN56OSDWc/Oeazb+J/yl1Nm9zVlHJX037HDt75uDX/Q/AKqnOoLqC6hOoKqmuobqpq0/9l8GpqA69It00a0+L/B4BX0/vAKxbGzd8du2IhbeYf3DzVlu1Yt1x/NHt8FsVJzqkXHU0rKakGqqulukfZc+Iz8IF1kVo7udRrs7JYbbCr6NVNPN3soXxnsStVnKUAqQBbedFmWcyO4iiUdTM3TtW1sgpxPGW2pk1ma0qZrSlntvDLdT5uzfGQ2YLqHKoLqC6huoLqGqqbqtp0fJnZmtqYLdLwksa0OP4BzNb0LmaLRXHDdye2WEib4Yc3LmMXT8UPgVTWNGkgzF6tZUHZ31VLBtqLBLJx80d7fu48e4YX3d70aMoR1+esyUu0vRDDUkxr2sS0phTTmg67TtEhpgXVZ6jOobqA6hKqK6iuobqpqk3DljGtqQ3TIm0jaUyLYR+AaU3vxLRYHLdsd0iLhbRZdtTpJVp6gcSJ/2KaKul1qewF1/XjXRC9lRfJ8hm6kNOJ4JimHQDx8KjFw6akmQwprV3NdN34OR+6wLai0Hk5p9LtIAicl+sLe7GozhbMKMk1bZJcU0pyTbuSXPm4NYtDkguqc6guoLqE6gqqa6huqmrT4mWSa2ojuUjDRhrTYvEHkFzT95BcLJj7vDvHxULafN7OcWX92qubUy/RmyqOyieFpb0oCNyTrqudHpR0HkqjvKy/OctEXG6rzCSDyzP4q7qUDulfK4Lni20/x9FBdvvzlwPJCZr/MttnXhTwLa3qDVQs3oTAphQCm467PsUhBQbVZ6jOobqA6hKqK6iuobqpqk2LlymwqY0CI30TaUyLxR9AgbFr3ACRsFBu8O4cGAtpM3g3Duzarezah/WGzmX0u8sRklgpL3CPp8R3DTVyMBSnX24CoDegz2ExntqW19VO0hJRusZH51RPzU+x2odu6LGJOeXCpk0ubEq5sCnnwnAdm3zcmqUhFwbVOVQXUF1CdQXVNVQ3VbVp6TIXNrVxYaRFIY1psfQDuDB2jVu3ubo2J2QBNlvfR4bRMDw/V99OkTnkUGw4GRvmfn/THdntvU/ZmDIV13BJPorw16accP4t5/i36dYeSCVhUxag2q7nTSbmeX+QbAXN9AazLplRemzapMemlB6bTrsumUF6DKrPUJ1DdQHVJVRXUF1DdVNVm0Yv02NTGz1G2grSmBajP4AeY9ew8yhdmwmyAJu97+PGaBipGnA+RnHR5qZUMsd9SaJA9p+9wPWP7OE9u/NQ8osK/X2YjW4W5o9u4MtDOTUqMSzlx6ZNfmxK+bHprOtkGwJkUH2G6hyqC6guobqC6hqqm6raMOysDJDNbAAZ6eRHY+yGZWFdDMuu0VIunIYxy7IAi2VZSItlaVj5TVq6eqZO4L5EZlkwn2cn8sgsnsWl9TF9NvkUK9N2y5E368B28pF+QdGb6fsZR9KBK++F5gTK1celTIHxyhlIV1rkOAd1jPZB9OKHjhyEVI4byPu8PMdVaPa2I0cW4VN/Z1r46MU3bPzq3ZWNP2uSZzNKns0oeYbxjS/5uFXjQ/UZqnOoLqC6hOoKqmuobqpq0/hl8mxmI89Iuz0a02L8B5Bns/sa7bEwbvzuvBkLaTN+N96sRHLK627eSS5HNomt78PPqv3priNnDFp0PMXqIP13XlXtZ90kUUkifyBOpmDarAmmzSiYNusKpuXj1pwMwTSozqG6gOoSqiuorqG6qapNJ5fBtBnr2PbTX2kvOxYjv+Zy8mfj7hRz801w2jUl/Oj89JKkptU9tjaDuo4q3rPOm7/SKFY0j35NtGgejdBfzodEHCBLxNjeJHitvGgf+n8o5xTpb0U6QOafVDssVnIQSskqtKipdKjdKd1rt9It8kdnG+kH6t4UWM8Pc4kpW9ICubfPzsGVdrnn7VbYcdmcU453kJ650vBb310iX5fZ7t45L9Ke9yC9ut1U/uYcbJ3PzjYi5qdU2qxJpc0olTbrd9wPy8etmR9SaVCdQ3UB1SVUV1BdQ3VTVZvmL1Nps4HN/JhKYzG3mH/waPMP7jJ/1/549Gvi5h+8x/yDdvMnpqdkhpLkfe/NM3b76gsJWqQFT2+kHaW6u6WYO/131ftfua9lXhFH0UltK8CKjHu8ZD1yZW6QBOc4VtvvnU3u6zfXNyv7iVKC1PiSFuSBT+xOkbRZE0mbUSRtRpE0fD7iSz5uze4QSYPqHKoLqC6huoLqGqqbqtq0exlJmw1tdsdIGou5xe7DR9udkWBBoOL95YfPx+PZgqazcO77zo35aMRNvh/e7Hs3dE+HS+B+84nnTWfq4iGfnPd7eRCLCSn1Qr/enVQ7Uboc0ZPYPPBP5sx18ib9OLO5/WfHPcoUQO/Dx9FZ7tM84mXEW5/yFGybNcG2GQXbZhxswzV583FrtodgG1TnUF1AdQnVFVTXUN1U1abty2DbbGSzPQbbWMwtth892vajew+j0Ejq+M6N/mjETY4nwb+LbfIpdLlQbulJn2QT/B+vherdnXISFew+HN3Q3St5kbauwbPhf7pujaWH66ET6egShTupUfYk1nfTi1m7e3FjVWp2/aq+dz7L8oDMA6TemSQAWbEzt+VIuaTY0S2zj2zNjsJvsyb8NqPw24zDb7j2bz5uLQ1A+A2qc6guoLqE6gqqa6huqmozDZTht9nYlgYw/MZibkkD40engfHdqAwL5Xmgc7tBGnFTHhjf/LofXJxExXp/u0BRnJdAKX04rTQXyF7/r2tqJAeQofXTPBvBzNuzR/tBua8X59Xd+7KgUIysU0WWsdyXbXTUfy0v/jc/+ikNN2vScDNKw83GXR/9kIaD6jNU51BdQHUJ1RVU11DdVNWm58s03Gxi8zym4VjMLZ6fPNrz5IK/R998yyY7C+N+79zmkEbc5HfGx1Wse4qkhvAP10n9/uxvZY+jmNafsurD8iCV86bRNzmSmnPn7KlPBv8sR2L0pprOMmkUfXWOZ+/gHKUpeLSTmb/pEKehdn3kTPA4XW9x23S5E0ZvxOkUkps1IbkZheRmXSG5fNya0yEkB9U5VBdQXUJ1BdU1VDdVten0MiQ3m9qcjiE5FnOL06ePdvr0nvNnLIobvXO3RRpxk9GnbQ921wnVm5Mo/w9h2IpZfQmn2fv6uZvN709x5KntOZbtsu2rz06h0buOjkpW7Q5u4oTytHYOrmzL5Tfwonbidhn9v89Jqv82CtX3zi/C2ukpfahUsbmQd4y87isQx1Nabtak5WaUlpt1peXycWuOh7QcVOdQXUB1CdUVVNdQ3VTVpuPLtNxsZnM8puVYzC2Onz3a8bP7NuW7tnuk3xO3/Ow9lp+1Wb5YFNO75753DtKLFP2WAi1+sL0mAWJthull4X5SGuFVzn7v3CR9coIo+po4Lxqn0f9megNf1vLMW7wcQ3djDea8uV9V9YFuGJtYyW5hzKfwlLGbNRm7GWXsZrOuqA1k7KD6DNU5VBdQXUJ1BdU1VDdVtWHz3scyZCd/shgdU3Y06Aan09i7rU6v2FJPwvopSM2nO2I+8a/4FsfT6F/MLP26JV+aPpvWH6VDbLpsqq8J9tM5/VEfQgn8/SG9vmPrwg9iVf0Ilpps+fPXNhWgt/fZSd2vynlz450bZxv0odB3so3/EkgXkSSNoiAp7eIlX/2T4zo7JaUd5RBevqP3dlC6EoUvR12jE9nVq91LOUP0PjZpvN5HiuPJX3UrL1OMXc0SWH7G8hzLCywvsbzC8hrLm5oMskWZzJM/8WxBel7SoJuyRe/h2aJ374K/9YPQhNGd2uPf8m0Jo2dNGPkKnhSTUrH89zYvNaVdlyePH0upxT2d4ugUyw7/tQRzvmDAEgP74Jfs9Fty3rvyhiDHXaWJn78vis2cEzkRKzlIL/oJTeheku+dn91Q0oRueORszS7g8VK9/TQKJbGxFEEpv97HJubX+0g5P/mrrikCkn5YfsbyHMsLLC+xvMLyGsubmgxSRBn5kz9ZUgRm/mjQTSni0dQfvWLrhKJ72847Yj7xr/i2/NC/JT/Ic1Z3ALyuwsk8PXZPF8d9ic+nNLiUU8R1ihGrV1+9sazQb8kKxZlYPfvwQ+Uc3a+6+66zUypwUl+TP5/1QVu9aJFG+mblzyUOqZj7pG7wNd8ilKQhla1YcqAUYO9jEwPsfaQcoPxVNzKoGLueHCAKiOU5lhdYXmJ5heU1ljc1GSSHMhIof7IkB8wE0qCbksOjqUB6xRtP4Fo/DU0S3SvZ8a/6tiTRigkeNXivq62/ubGG8E9umqo4rC80moRyiqPjKS1RRNdlPZYr2DdtXiJ2MjV40suLBmVQ7tb1DurJCZV+u/B3O/nnNQsQesvxRdKV3GmOGuRTCs0PnsPUD5w0Okax/PbK9EPK8ZxOUqWeHxyo3Wc1bTRxwt5HyhPKX3VbmyjGrqcNiBRieY7lBZaXWF5heY3lTU0GaaOMFsqfLGkDs4U06Ka08Wi6kF7xBsDA+kloyuheC49/zbeljNsJQ+Wl0cn3PlwhgzyFJP4+TPBZgytsUDzb88MEDDqk95SlEFduyZxLuN6KHEV8kn2JD0Ifb52TCl6lVaMrtXi3/h9/+NeskpyiVDOP2YQk+urK5qZzjEJfKmjqPQ0rjFS7xWr2aFKJvY8US5S/6jrpgGAilp+xPMfyAstLLK+wvMbypiaD7FEmFOVPluyBEUUadFP2eDSkyK94S7Eu62eh+aN7YT7+Rd+WP0Zt+ePT5+ty5TVRdEOS6DCfndfo6EuFnqMghHL4SZfykJ0NJS0xpKpmtNsp5ez1v2N55VJvZ+oFT5kxhKnrSakCncVYK/PajVSN3+QQex8piCh/1Y1KKsauGx+yiFieY3mB5SWWV1heY3lTk4Hxy0yi/MlifAwl0qCbjP9oLJFeca1CN/jh71bXd++2ekfMJ/4t3+b68e3nkcw8v6j380O5DCacMrS/Yoztxw3NiLvADb9mE4DsrUPnCn1kwdQcKrZaz7Ev5X1lSlB6tcg2NaRIkCxXFIeU/KNQVuyYUu32qimiiS32PlJuUf6q65sFJBex/IzlOZYXWF5ieYXlNZY3NRmkiDLCKH+ypAjMMNKgm1LEoylG"
    "esW2Wr3Wj0ETRPcyf/w7vi1BTNoSRA4Gm7q5lTeJH6uzgx9q5xbfDnKYuDj1EOfXYtliYn+buBbuPeoDC95ZstXBDWTrMsm2awNfaeQqu+t3HFqu3U81PTRZx95HCjvKX3U7y1CMXU8PkHfE8hzLCywvsbzC8hrLm5oM0kOZe5Q/WdIDBh9p0E3p4dHoY8vd6Gcnv6FfreE0SXQvGsi/6duSBCseWIYc/XDrv/pb+eL+kBY6euGgyBBeJNN2XZWo2Mv44XRw46Pr+Um2lKlfLnQZI73XKMwEyxWsUKNz9BPZc73obhxb9yL1feViBoLOtltO+h8m3wMpvWnol4z0LcoIiTTaZisOop9PetWSNaWt3VQ1YTRRyd5HykrKX3Xd/YS0JJafsTzH8gLLSyyvsLzG8qYmg4RRxiblT5aEgblJGnRTwng0OdlyN+0Jo3v32jtiPvFv+raEMbshYeRVPPOEEZ/3H3T5MnMA2vEC5caCQBQLkiUGKzkpz9/5nlmkqBRKkSpou+znWPog95clgByLgNkiaW6PurEkMOeg4hcpm3Q+nQJzgrMgxA7K09ukOn9cPyN9M6EwZu9jk8bsfaQ4pvxVN+y6GLueSSCRieU5lhdYXmJ5heU1ljc1uZlJehUws2cDM0n/XBp0SyZhsfdnEnbFZXLxDoJhkxRi+xQshXSP+cS/4ptSCIuW965I9gZMWx//VWgEkwP8SHpQ/1EqmKI9ml5KLyaxSqJzLF0ADP8U7D7IJMQ212B3ovc8BdXWznZfxOiHc6znOMeLXDqnpbItUvMa43kyyZESitJA6BTdfMiydiOVrNADAGaPA5i9j11fSPKxa1kBys9YnmN5geUllldYXmN5U5NBVqgAmD0bgEm68tKgm7LCwwFMdsWWoxnWT0Gzwh30Jf2Kb8sKvbbliq06XLbSwSMKf8hPW/tBoNcAmtug2dtJ6h8ljTSPRLGUwOnLNNpuZUVCyEs5gRWrk9KdCa5rmuZgh3pz3pTeZJVpUHGO4xxqPFPOigdKnS71bZCvSp2cNzf19BkR++Zn9TarCQPgmD2OY/Z6XRc487HrCQPjmFCeY3mB5SWWV1heY3lTk0HCqOCYPRuOSXoD06CbEsbDcczenTgmi6MVVmnE36JwT5LFu1BMFr28zhSuE4NinVKWH5w4OqdCR+pjG1s/8c767aJxenvnBrJQoVyhKi24NrsVPYcYTZ/M3KAo16JrNjQ7mZgkYRYlPucFWFWJ6syasnh6yzpb8jBlHN8OfiDnRTSt+b3zOXWSU6zcrZ6JSF0otZPGScdsqqJhUFMnxpwtkRrNksa+d34/KFMUUiC8rePqClOfncRNnW30FgLmSy/X7nX/U7P240QnFSYFC8ayF+dFe4AX7XFetEd50RFBN/Kx69kL86JQnmN5geUllldYXmN5U5NB9qrwoj0bL0o6G9Ogm7LXw3lRdkX72XMaZkleg87J612IKIvO6kuZSq27SL7xMPus0vdEV2pPdY0pN6zgoCrU3VDzNJftjbJ8xStKHiN9WKyoKenp2YkkxWP0KpyodDnWLz1ZNpFZUF5ULjkpt1gIMa9MqQqdox+eU5U86XaLco4tkb7MSh1lW0fXu3b3uhzNxpf1IN21Of8g8kYXvEpdK7+yLKMTUPmAS35APlHKLD9ZafXqN1DNPgA77XHstEex0wF72cLYKZSfsTzH8gLLSyyvsLzG8qYmg+xTwU57NuyUdFmmQTdln4djp713YKcs1pKChp1T0LuQUxbd2BvuBJqW61ibKhmxOkZpa+1qejt6DpXNfNKDL8fgY/+o93/y4lcKcewvps6t8+rL1O6pqIhpZll6iiO/FrGev/gvyfdO8xjNm7zlyUTNdKUy+1nldzYh1PK3tPz7kMVgyVRt8x+OrvYAutrj6GqPoqsDQrDlY9czEEZXoTzH8gLLSyyvsLzG8qYmgwxUQVflq+UZiKCrLOimDPRwdJVd8YbztizUkoBGnRPQu5hVFg3oNfPq5HvOV5VGwodKIrkemUGJSDMqsZsW52JNKS7ZLFbfTkpySGg6ULOE1K0Gp6wI6aUfnTD2wdnTm9zKFeI2qUBvlSJ8T85W1nxi9+Rvr+VBsgWj0JOXT12QJI7eEg3PF+knPahLCZ5V39LYLY7z6s49MkeSqZjkzvyO0kheawOWlThX2wNcbY9ztT3K1Q7YmhLmaqH8jOU5lhdYXmJ5heU1ljc1GWSlClfbs3G1pNM1DbopKz2cq7XfTesmNwu3ZKZx58z0Lq6WRZsNbrM6BPa43TD1vciVtRBpIq88PfX4sbx31TyOI8s47n9Lv76MzmfpiNK2JXS+NLx+BUs1ir/zX2I/CEyy08s/QfDkHPxU5j4yY3qqVhhxnbcoTkxvoHxCZV4xZb97f5DVKd+8FAa66EEUJp4sxZv0lBUakHokkniub6lbdXJjfRhQDhPKmlO+FnWMkjS46BNALDFxmrcHaN4ep3l7487TJUzzQvkZy3MsL7C8xPIKy2ssb2oySEwVmrdno3lJf24adFNiejjNy6546/FiFm/JTJPOmeldQC+LRu2HEnWSWVKnlzaWfGi3cScK5CXK3Z4DA8Q4rsH448v1sIEBeN9KRcqvddD0xCe4ZPtmb8r9mnUEd/Oeg7WXsmxKZZaq9YmCnA8upl85wyOTpyiUVm3FklE+HQrVt7y00w2nlKufv5p9ACzc47Bwj8LCA0Ls5GPXsw+GhaE8x/ICy0ssr7C8xvKmJoPsU4GF5cd49iGwMAu6Kfs8HBZmV2zdm+/aV5xGWLLOuwhhFl1eKjJ78fH13IRucyimhZmnepiApZ2pvaBilm/Kg1Zyzlm/Oondj+fEC1RStEIUTVZ9JC+YXKSepCOqbskiq9jO7hxICg1TaaGYbeCbQo3q28E9J8VuWVYaMpC8dHEkvemrl0q/ZMcYyi9uzs49+qYHbOqHZ+VEL4kUlGrf9OcUcg9QyD1OIfemnedBmEKG8jOW51heYHmJ5RWW11je1GSQiSoUcs9GIZNe5zTopkz0cAqZXbGlODuNs2SiWedM9C70mEX/UmqZWCrEXBw2KBdfL04tXEHCRkH3gwpOOXusUYAwup0GmNkrPB/di3nPkhc3eW1zzuHXMHoLnfB8fDE7+66nUvfoh9FJTlmlMoVJk2K/6xCd48Rx95HeUfNkoTuU9yd5l0qcnT70UKWYi7lPsbF23S7TO3bygVnK4bhyD+DKPY4r93j5WDb5wbgylJ+xPMfyAstLLK+wvMbypiY3U06/giv3bbgy6dZOg25JOSz2/pTTvxNXZnE85bAInnLo13tTyqGfjBPJOnMUyeQHL/blRSxjmgvKSIV7abrky+GD9BBtSyQSySzsVn5ydrEvs6pEH5KWdeF8Wyw7SOGcAjc0XeWLKo8ZluRFQaA8YRj1REm5YTbbyW7zzbSZuUjqSqOg3DlSJl7SwT49KD+WZa5XN2t2Gyid4A7qaDrEk9RS/UCV1NIHzHOfM899yjzjpudfirFrqQXKz1ieY3mB5SWWV1heY3lTk0FqqTDPfRvzTPrB06CbUsvDmWf73bQuN7NwS4bpdc4w78KeWXSjSnWl7mzl+FJRd1Z9OwWyt10Uos5Kx1XOUJkqk0+Otq9pXZV1iTJvcfkkgaUh1uJew4L6wJRZHZcGGuXbfKpwja7z5m+VARWd2E0OT9LPVq9cVfbqj9FZ7i2K9eEswQFM40xzBj3b4CvVvNQry1vHT+snP93QwE1ZqVu9HOXHcspDT+v07JAlKs5a9wFr3eesdZ+y1gMIxXwpxq4nKsxaQ3mO5QWWl1heYXmN5U1NBomqwlr3CUP70182tN09D7KmlJ9pnPFrNT2VExdJUIzaVqGerutE5Ydk0ZlF07YZ/O5p3wwa8vfQDZM3FcsLBklOlq9YEk2+k6MSWSwR957c1Fdh+qGYe/jhTjA/naii2FHf5M3G/NFP9JFuvu3Fhv+LxpMjQRR1yytZUdEzETfNN5V0tdsn500k9U3+dmsW/2VmY85rMbdzNrkP2OQ+Z5P7/Y6dsIqx627HbDKU51heYHmJ5RWW11je1GTg9gqb3B/Y3E7YZBrU5vbBQ90+eN90pGuPe377FrsP7rb7wG73XRwdcTGIa9Fovb0i5yBlE6gyTTHonU4P5azAvM++KjFzcHEO0Zt0rr04Rz8I/H3syvmOazc8mQsk1dIP1vL21eGqrgdMcJ8zwX3KBOMa7l+Kseuux0wwlOdYXmB5ieUVltdY3tRk4PoKE9wf2lxPmGAa1Ob64UNdT672i8FaU7q7wwItfu/c3J6G3OD34W2PdzNH/p+zPFN1lVdH9ozVDQ9wxvUmYtTfXn7qec5WXl7i6JyIqf39gRmUI7N9gMz2OTLbp8gseypjYhbKz1ieY3mB5SWWV1heY3lTk4E/K8Rsf2TzJyFmaVCbP0cP9efovnOOLM5iz86d6GnIDfYc3fA4vlZyNn+WlbowCov5d/Y6zwxKa7qa5UF9wFCWJqPjLorT753fVRBISwk9p5alg4PvHQQUi68zbBMMR/yv2ohVHwPItM8h0z4v3grnkF+KsetGxpAplOdYXmB5ieUVltdY3tRkYOQKZNof24xMIFMa1Gbk8UONTK62CG07lyzKYuPOjeRpyA02Ht9gY8SVCpPgKb2K9+K++PIlFvPsVzfwt7r4gDnH7KYuszgZXlcmkSf4JXtBPqlYThfLtoSsKHq6sFq2YqeLu5m7yY7jaIZqJ1uuF+XGrNpRdfCq2wG52efkZp83kIfPpi/F2HW3Y3ITynMsL7C8xPIKy2ssb2oycHuF3OxPbG4n5CYNanP75KFuJ1dbmrNWNsd37STP79zi+MndjmcoqrRx93cXbaBs3/+HnfsSy9pBViet1GLaD1/l57MCjGZ5IZFFNGmv4KidwE50mX5icb2cjpFb0N3pXqVvdNEzsnRlsb/8lL6rufoWxe6rz86OVMerGh1Akn0OSfYnnR/rGJKE8jOW51heYHmJ5RWW11je1GRg9Aok2Z/ajE4gSRrUZvTpQ43OcEsVKsvLc9cu8vyuLSaf3m3y6U2LZamKT7Eye2IC+2QTc7V19ubTy0b6OWBNF9gouvH78VJcRL+Vazfny+BvfhA4e5U6PwV/HJR/VLHUSzVTdGZizhf2AV/Y53xhf9p5EQzzhVB+xvIcywssL7G8wvIay5uaDExc4Qv7M5uJCV9Ig9pMPHuoiRnt575EGX/bstfVtUU8/wAWP8/u9jP7lpOvxcEB84Vljn1yzqGfZrxMrHYqFlrYiWU9q3L4dH9W1kUyho/mR9K1t+U4uvtiSmZkZQW3kgPkIJdy6dY1x/f6AN/rc3yvT/E9UrY4H7puaEzvQXmO5QWWl1heYXmN5U1Nbhp6UKH3Bh9thib0Hg1qMTSLu8/Q7Gpr17poxsK4jeltcxuzkHYb277b8pp2GDn+Ud51o1gK+UWxfhnOiN8tsSq7+NWORVWu//tD7F5kC4rVgKheq2LNAcDfBhx/G1D8jbD8+dA1a0L5GctzLC+wvMTyCstrLG9qMrBmhX4b9CzWZC3XaVCbNXsPtWbvPVAJi7Y4tNfdob27Hdq7fdfpf84qMZvHyVdT19dTsfxUenFe1EWqBbuvrh/oY35KrMvRfDauHFm+RGdnf5aa5KnKZtDHUuFAeWHW3Jlh5JijOSc2AJzYgHNig17Hh20+dN3RGBOD8hzLCywvsbzC8hrLm5oMHF3BxAY2TIx1SKdBbY5+KCbGrnZDMRcWaivf2z3mE425wdH97txIqeC/u5VCJpWq+tfSKbHaS7UWM8s2Z3ZlZTwKU/WNvTSz+/ksC11FlRQ5PpPtc4m3BW/XeUDeqhsVXPKg9HJSTxoifZJ5d5A8yQTCoKVZLWIhVX/L6RRTmEW/KNR4FFNJL+TzA86hDQCHNuAc2oD3VCdV6vKx6+kEc2hQnmN5geUllldYXmN5U5NBOqlwaAMbh8Z6qtOgtnTyUA6NXa1tx5vFWXPJHT3UWcwNueQOBu0UR6a83LUrR54oLBtjbCQpcCtng7VVs6M0ZoNbNuICdTS1LKWav04csoxvFsrzKndP5pXdLBOYDKFP7/nppZQa9L7ZFUfVdXpZLuB02gDQaQNOpw14o3T2soDpNCg/Y3mO5QWWl1heYXmN5U1NBrmgQqcNbHQaa5ROg9pywUPptME7KlWyWGs+uKNBOou5IR8Mb4FgVKrio69LnVwrVr769V1zveF1ivVpvSJFtBZAYbcgvt3yVujfO//Ihw2dc5DGbiL/lE9lBl7nhkMUH/XZYOXKwRaZCCW6IIGejlwPqrgGr72O4ifl/XmzNhiwIkrVT1HNIQCgG3CAbsDbpZMdunzseg7BBB2U51heYHmJ5RWW11je1GSQQyoE3cBG0LF26TSoLYc8lKBjV7u1eBKLt+aROxqls5gb8sgtMJ2fbdBnu3XXeiJ5AslXBMwTXp9S04daTlFWpL8Na2e38Q/N0V0HvE4L/J3jBoHzWSeEVPA7yQp+ku/zmRxkaiEVrRFZDuDw3QDAdwMO3w04fMfeKTB8B+VnLM+xvMDyEssrLK+xvKnJIAdU4LuBDb5jndNpUFsOeCh8x67WUm+fhVmtf0e3dBZzg/XH3That1J230+iWKqc6Z+SpJBEgaZ1bqds2Q18diLPc825XKngEcWyXx+6R1lC0Dv82uNmWz9LB1s9P/Bd5nAO3A0AcDfgwN2AA3fkUH0+dt3hGLiD8hzLCywvsbzC8hrLm5oMHF4B7gY24I41PqdBbQ5/KHDHrvaLkoeWzeN3NDzvHvOJxtzg8clNrwk7PzRT9UCJ7a6v7MUTvnxAVTp6yh4hs3VLV3N9BD756ktL0yjNFg2yOmPbrECYXhuQs2xyYt2U7TmqwA2jI3U4J+0GgLQbcNJuwEk7thaASTsoP2N5juUFlpdYXmF5jeVNTQYOr5B2Axtpx3qX06A2hz+UtGNXu/F8qi2c+vyOnuUs5gafT2/fPCza+ur9uxJ696M+zSZLdIZ810/cH0xfcFM141ouo9y22JTOYNmA9i03x08PsVKVA7FJlhE0qKd3IPLJvSmpk80DfibrABf9qfIaX9kR170uicEyB8f7BgDvG3C8bzDtvAKA8T4oP2N5juUFlpdYXmF5jeVNTQaZo4L3DWx4H2tiToPaMsdD8T52tbYCpizOmjLu6FrOYm5IGbObpgZ6HU33hQjAtMDdK6mangjnaPYi9Zt+UKrmzvICx/tM9VA/cf7kOoGfpoFyXtTBD7ff/6mwfQoP3NVvN3tHKap/sQzAccABwAEHHAcczDrPHTAPCOVnLM+xvMDyEssrLK+xvKnJzQwwrPCAQxsPyJqP06CWDMDi7ssA7GpzdTrYFgBYnC0DdI/5RGPaM4Dt+y1PGr7621BdnN05NM/7bK7+ohf2lO4oVa5zkdHA5b0+QylY4QT60S9Z1zoncX2pblPcT8H/Rrvd943EIJySPrQX7RzvEEdS1DwLtNP+1RupJIMhABCHHEAcdu45no9dSwZQfsbyHMsLLC+xvMLyGsubmgySQYVAHNoIRNZznAa1JYOHEojsam0lPVmcNRnc0WucxdyQDHrdVgNfsmJTUlDTD/fCGR4j+WeQWnWpm7LVATaObsEie4Lf9LZKVopXOnp+c4/lZT/B+gsCQcrnfPOlvGj+sGeu5hDiEECIQw4hDntdT9zmY9ddjSlEKM+xvMDyEssrLK+xvKnJwNUVCnFooxBZY3Aa1Obqh1KI7Gq3ccUsmhfTZBG8mCaLuMHXt0CIR9OitrByaUXwOuc3dTReVRy4J72zXnDAYJHwh2wjkGUBcld/lRNFb5HzptTXJHe5bOXt3NTfn9VTaWvA2fp//KHbvz05p0gmCIFSpyepfLUtejQV55C2Z0/qa55OKvVTqQV+RRx1e0phL2VOcTyp2E116/F6K/IMf8z/wovOYfrkpIdLLMeS8+mR3voUkMnQj/I9JNnJJLOs4kXh1tcTqawwaaJ3Ms2x"
    "4uTa55dlMg5ADgEAOeQA5JACkENyGjEfu57JMAAJ5TmWF1heYnmF5TWWNzUZZLIKADm0AZCsSTgNastkDwUgh3cCkCzOksM6dwdnETfksFvgx1rjOV3/o1S7o1khxA9P5+zVRP/wMdqqgOUrCkW6RzG0p+JQ0ovu731wTdOSDI9009SV9relAiHCOFZSUH7ASnKQXlPxDlGgqYUoaCai5BjpfC3zrHPydG24mQtXitxglllnlWyh5nvnk2R23Z63WeREvgtSpKj6LVRTD+Ath5y3HPIO4aTaWD52PfVg3hLKcywvsLzE8grLayxvajJIPRXecmjjLVmHcBrUlnoeyluyq924x8LCLRmoc3NwFnFDBroJt8waP76qWO+iNjZdzMxIVkjPpvMkPL2hNzDsBQTZ7Zh0JHXPK4XPdP74IL3lNApaVAJNo7z+91N90yXv8VJUOtHbLuaIR/JUXxLSScZ0ljOHwqV9lF78bVRGk01dU2f8VcVmwUiuyTIOpzOHgM4ccjpzyDuCk72ZfOx6xsF0JpTnWF5geYnlFZbXWN7UZJBxKnTm0EZnso7gNKgt4zyUzmRXs5dFY1GWRNO5CTiLuCHR3MJjysKmGNlsyta2ZE5uetAf/weBNCw5ZNR6zkOvt7jOix+dEnNoW22zemfssEdWDc2cBytuRUh015dTYdk9SUOm7AhZFBctC3yZOyWOaX+QvTOZRVxfIyC6gXe9Pltyjl/9V6mxfq0Hx16dOOc5BJznkHOeQ97Jm+zz5GPXswnmPKE8x/ICy0ssr7C8xvKmJoNsUuE8hzbOk3XypkFt2eShnCe7WkvdBxZmSSedO3eziBvSSQvjmU9RcluWt3ayEk213R1Nfv1gSkOwzDJu28rRK7W63cnPvzuJENz5jUift5dtJMtI0jXB1825syRjGsQdlInIas/E+T9PVq7iOuMoZRVJXYle/JGKcX4qZ9HyPBbF+WwmSaNQ4cpx/1X7UNXcAQjSISdIh7zZNiFI87HruQMTpFCeY3mB5SWWV1heY3lTk0HuqBCkQxtByppt06C23PFQgpRd7eYiUOwClizSucs2i7ghi7RQpGaF1aBj2e5v4L6YauhJUQ8q9Y9F/6JaXShWrpENbI535K0fr+WgzGpOdf6SREeV3YrzpmKlq6mbqo7yN1oKorfva5MZA5Toi8oar8oaUV4/jn7jqX2KUu5xr4WfTZ14sxGuoXWWYjjCOgQI65AjrMNJ5+kJRlih/IzlOZYXWF5ieYXlNZY3NRmkmArCOrQhrKyjNg1qSzEPRVjZ1dqrwrJIS27p3EubRdyQW2glR+1FU+y1qGGjVxdcp1QcVh7x7unyo9l0NpaPVeBXSt/oxtdhURKHZRveWlsv0ZikcswG+ZNZU39V3z78P3+SBdSjG5qWs7HkJYFmvSiOQmn44sapMt2/dUIQ9F29qtDZupd8b6hYBUpj3w2yRJFTrXKsLV9Scd6i+CvdHOIs6xCwrEPOsg47s6z52PUUgllWKM+xvMDyEssrLK+xvKnJIIVUWNahjWVlrbBpUFsKeSjLyq5mrzfLoizpo3MDbBZxQ/qYdTkHLz1prm822WmWXaX87Ksb+25IC0iz8Z4vTiIzoNCT16iscp4s6Or93Xymkl88Xz1p7v/IXEGK1yZP+Q/nK69e4CaJnKrL93Xk/SVJhbsFOzzm4GyecPSy7ud8W18Fl5yUZWmEA7FDAMQOORA75O2t2UwEA7FQfsbyHMsLLC+xvMLyGsubmtxMI6MKEDuyAbGsvTUNakkjLO6+NMKudkthDRbLkwmL4MmERbQnE9v3C4tq7JRw5gf9gdlROTsIw4bUOzlZSQuz8FnkCn2yvVo64xSr0JVbqdfQMDeY34JDavrpVpEqPSd6+TWMioq6fuorNtWo3nklR4wAJzvinOyIcrJ4x/NLMXYtR0D5GctzLC+wvMTyCstrLG9qMsgRFU52ZONkWZ9qGtSWIx7KybKr3UbUsWhLlujcnppF3JAlOhTqLFZFmnU6deNqmSaorfMiHeKzFo269I61Yie9dQ3m6v6vx4uz8+PETB5M7wyhSopTM6/l15HPjneOY/PukmG128aP6ClENmvIWZbdWUA5sppRvctqfgDE7YgTt6Ne5/yAiVsoP2N5juUFlpdYXmF5jeVNTQb5oULcjghE+fviC28PTYOiryp0ft3tfM9XoUc62bPotQrUq0xIy4mCpIZ3wbYsmhfxZRGWIr4s5Ke2zGCNc1zPO8eunn7LoqlmxXr/3//5f/uOtIkWw8sqRaCS5LpwkfWXTJyj4PBmG5Wlhb69o5WuhcMe5hwqHQGodMSh0hGFSplXMVMK5Wcsz7G8wPISyyssr7G8qcnAqxWmdDSweZUwpTToNq8O3u/VO3FSFmdxafeGziyk1aWD97qUGXBgN2AV42RO5IzlCDCWI85YjihjSc6p5EPXnYgRSyjPsbzA8hLLKyyvsbypycCJFcRyNLQ5kSCWNOg2Jw7f78Th3YWyaSg3Y/duyyyk1YzDf5YZh3YzZpWrmQs5dzgC3OGIc4cjzh0SF2LsEMrPWJ5jeYHlJZZXWF5jeVOTgQsr2OFoZHMhwQ5p0G0uHL3fhfQSyck3G/3Eg51bKrMImwdHd3pw9M/y4MjuQTdJD7SgUzW4akEA6404rDcadbUgZvWg/IzlOZYXWF5ieYXlNZY3NRlYsMLqjcY2CxJWjwbdZsHx+y14XzlGFmYxYPdmyCyk1YDjf5YB25oc+/vY9UM6F+XM2wgwbyPOvI3GXS2IkTcoP2N5juUFlpdYXmF5jeVNTQYWrCBvo4nNggR5o0G3WXDyfguSS3xykzSO5FfS6sTOTYpZhM2JkzudOPlnOXHS8ij0fE3FBedvzIycDhsBOmzE6bDRpOuLIYbDoPyM5TmWF1heYnmF5TWWNzUZmLECh42mNjMSOIwG3WbG6fvNOL2zeCkLtPiwex9hFtLqw+k/y4dTuw+V94fiU1JOV40AXTXidNVo2vV5iOEqKD9jeY7lBZaXWF5heY3lTU0GFqzAVaOZzYIErqJBt1lw9n4LMkJKtTiwc+dfFmFz4OxOB87+WQ6c2R14UMdoH0QvfG2Gw0kjACeNOJw0mnV1IWaToPyM5TmWF1heYnmF5TWWNzW56cJxhU0af7S5kLBJNOgmF7LoDi4c31mnj8VxF7IIiwtZSJsL7XHvcOHY3rJXb++bY1HSi4s4sXqRihPHAAEacwRoTBEgUg4iH7rmRCg/Y3mO5QWWl1heYXmN5U1NBk6sEEDjnsWJrFcvDbrNib33O7H3vq45LN7iyO6NellIqyN7/yxH9lreEJ1X1xMwgpmR8zZjwNuMOW8z7nV8P8yHrpsR4zZQnmN5geUllldYXmN5U5OBGSu4zdiG27A2uzToNjO+H7dhl2jbwmdxtoqVLMZmwztRGxanKxu5uiSTn0j1OiFfdY2SHx33Veq0ncNQeSpJ5FzOi+t93WuYkZmyhakx/S13+THAF5W+KRU6ySVJo8D3NEm39d3sTzcBANUhqz4GKM6YozjjftdWNfnYdSNjFgfKcywvsLzE8grLayxvajIwcoXFGdtYHNbglgbdZuT3szjsEjcQACzU6uXuQA4LafXy4BFezlHV/AgMMfTgLkNLPROnp+2s/7Nf1FxjLuYYzxhgPGOO8YwpxoOfOV+KsesuxhwPlOdYXmB5ieUVltdY3tRk4OIKxzO2cTysNS0Nus3F7+d4+CVaCAIWaPVwd46HhbR6eHiThw1b7+wi75yVjxbD6Urup3N8YoXAPtPr576Vby86qjS+SDN73YaCOZOjPWOA9ow52jMedn1pxWgPlJ+xPMfyAstLLK+wvMbypiYDY1bQnrEN7WH9XmnQbcZ8P9rDLtHCFbAwqy27oz0spNWWI4st9RqP6YeQP1j1S6vjRceTlNYybmWOHN31JHWdRPl/SFdYfcrk5AfqlLCCXdUxql4FDNCYM0BjygDB9cwvxdB1r2IGCMpzLC+wvMTyCstrLG9qMvBqhQEa2xgg1peVBt3m1fczQOwStwEILNpq2e4wEAtptey4o2Xzc6fnMFamBeu1VkRWd49ZeHyXhXVZ45dzbAr/fPp1/QuzL+eHxoAfGnN+aEz5IdJJJR+6bl/MD0F5juUFlpdYXmF5jeVNTQb2rfBDYxs/xJqu0qDb7Pt+fohdohVZYIFW53aHh1hIq3Pt8FD50fpUnPD6YBqpvLn0jZXVwEqcUxLFvivFP3Wlib0srTMrcnpoDOihMaeHxry2FLEipoeg/IzlOZYXWF5ieYXlNZY3NRlYsUIPjW30EOuOSoNus+L76SF2iZu3au7ojMpibI68EyOyxzlbP1a6KLU8x15iX+0C6kJyJamo4Iap/+JHUkLHPHqdV19Oskp3NP2IpqbkPNEY8ERjzhONp11fRTFPBOVnLM+xvMDyEssrLK+xvKnJwJQVnmhs44lY41EadJsp388TsUvcUmCFxVoN2Z0qYiGthpw9zJA2jGgr3cKOKoxOuhKDtAxjFuQw0RjARGMOE41nXXdNMUwE5Wcsz7G8wPISyyssr7G8qclNC04qMNHEBhOxzp806CYLsugOFqSXOKizfY7KIm0GZDEWA7KQNgOyuNo6rZ6mxn4ShcR+7Dq/RW/y5hglqYrcOD3EUmy5eIlMTQmlOPsW/a1T/AzxZ3Wcij8nADGacMRoQhEjODn7Ugxd8yeUn7E8x/ICy0ssr7C8xvKmJgN/VhCjiQ0xYs04adBt/nw/YsQuYW/9wKKs3uyOFrGQVm/2btsHzZrzcW/22h6NWZeGWOk2M1Foe0JWr1Z1IOCKJpwrmvQ6TlLzoesOxFwRlOdYXmB5ieUVltdY3tRk4MAKVzSxcUWscSYNus2B7+eKJndyRSyO1/ZiEbY+uCym1YL2Cj4q+17T4PIfjh96wXmrTMEt3ePJD/3j+ejsXC9NnFApXdAzku6aWSOl0qqtF0gPOGJgSh1dDAlYaSwnNQF1VwRd6kvMHW9913PcOFZJylzNKaMJoIwmnDKa9LvyCfnYdVtjygjKcywvsLzE8grLayxvajKwdYUymtgoI9ZFkgbdZuv3U0aT+ykjFmpxdmcu6RONaXX24FZnm3J5mi9S306u7lPkvKhLJPDPtaafNGtU0mvNT47MxxQ2kk4oKnEC8W+0y4uROKZwoMEEs26zkkBin3arrw5R9THgjCacM5oMutKC+dh1H2POCMpzLC+wvMTyCstrLG9qMvBxhTOa2Dgj1pKRBt3m4/dzRuwSLTgDC7N4uDOX9InGtHqYVTIyfZRNAzKpk6c7sp7SfMocXIpNUtfZnQPpUB9H8lA+p7KDwirqsfHEv9KCyHXS2A0TSRuOn3gHdRTk1zyVk1QKZr7knR8DORBwlHKfUs/X312bZ2/9RBoTuYxXqt5E1eGAV5pwXmlCeSWMy30pxq47HANLUJ5jeYHlJZZXWF5jeVOTgcMrwNLEBiyxFog06DaHvx9YYpdoeQXu3P2QRVgNfieuxOKqBq97Wz+vi3M3zMujNi8nXqyULuuteURdCXfnBon6cIoSP5WX8KyLD3Mqp5UmgFaacFppMuqIO+RD142KaSUoz7G8wPISyyssr7G8qcnAqBVaaWKjlVh3QRp0m1HfTyuxS9zYGJmFWxzbGXD6RGNaHTu+ac1KWlrIlmiiP6hziv3Q80/BtS17pXf7NrL0PmYjZi/HvoBQMozuMiytkLN37yjrLqjP33ixf9LffNEL2WAY+l1e92V2fvosdj9FIZ97c7xpAvCmCcebJhRvwpuUX4qx64bHfBOU51heYHmJ5RWW11je1GRg+ArfNGFN7n76nVe4pkGunL+8OD84P0fHU6C+Ecf+TK9Qrnv/owNTwI/OLXnlFzrELe/ZnQsosQhrQrgTgrLHOW4QlF6gT26cJtJqL1DSv+siD19zHk9tf3Ri5UXx1lHh9kMafVDh1gmyf0J54kfn9CQ9SeXrZoAj/aqy+UTWps+c5HGkK6iul+9Fx2MUFlN007Jwq7PGS9bOXc9GLieJ0nOHND57/39t17bcNo5Ef4WlZ8Wx5RvpLU/VbrLJzqSsa82+QyQkYUIRXAKyo3z9VuPCm7tJShO92cdugaSNw0b36W59MDNNadH0H60LalIGIsN6pGVYj6QMC9f9fSvXblMGrsNC4SkOz3B4jsMLHF7i8KoFI5TR0GE9hl2UQYXdwr9NGeHlKSM8M+J+cqMnyqKTL86UaHXbYXxREoNjA2rvhwP2/u6Y80LzzCTBYP+/gRehgz3T2gz7NJN3IKdtBNHOjTHzszSPNcfrhv9oLd7c54iy65FWdj2GJx/acWkXCr/g8BSHZzg8x+EFDi9xeNWCkX3ekHY9Rl37nArLRX97n0eX3+fRmSWClGHHRj9ZLfaVtOnd6NGlNjrxwZ/9C9u9zm234dpb3eG6ENttudlNhF+m5qwgsh1L6/UU1G6nRWSPiIjskRaRPZIiMrwu/Vu5dnu34yoyFJ7i8AyH5zi8wOElDq9a8PvdHjZUZOF1124nQnSk0eDdTn3CL9zt5BKDapkoa3rLUxZdW56y6dvy3XZ/Y8uTt11/t0Nhknmno+68j0iwPC8ki3cwe0f5fH3GtjwQ1HZvrt7Y7iGiSQtpTVp4ferL3a/d2u4o/ILDUxye4fAchxc4vMThVQtGtntDlBbedG13ItBHGg3f7jeX3+43Z+XlKLOOfX6y1u0radO7z28utc9vel7tZqP7Lub0Zsc8eLvLKQe+uXJzjyOqt5BWvYU3p77S/drtPY7L3lB4isMzHJ7j8AKHlzi8asHIHm/I3sJJ1x4nahdJo+F7fHL5PX6mNI6y65Knkg+EHHxJWfRucsLu90zzLaTegv0h1Sao7+uQXapO/QM6SoJMTe6FDtRhbbgACqPaPGBdcPOUY3kgHO7f6XsIcqZNOp4nB5db2bEsgQwD6PEUvN65cxJiWcgMOgexQtdmXV4Fn5uRvr9kAQqc70bXJwuMY4BfnMDP9CCCRtKvLD3AU6iOFetCsiSImeZbWQiu4IhRHi3GPgzKc1YwGNcbpGLDlT6mpoAFOoYpK5/3OQtlPjkvZMwT+ClFZbTUL0SkfiEt9Qvp2X5EzNGv3aYyXOqHwlMcnuHwHIcXOLzE4VULRqisIfULb7uojKj9JI2GU9nt5ansfDkgZdrJZrcns9mZckDKrmKzRLBtJpXzKfLU5WqdR2G9B9i4NIVRWQlq7S8wLbzZXWxcYyuEc8prBMY5qINzbBI+dryVymz7AeaVY/dQJjKalFTd2lXwjfPc/J5r3CSLLctMjnZ9DJStbqVoh1YmhogyMaSViSGpTJwQpTt+7Tbt4MpEFJ7i8AyH5zi8wOElDq9aMEI7DWVieNdFO0R1K2k0nHbuLk8753ZJoww7SefuZNI5U79I2cETZwUP9Jv0LgRMhCmkUoGCqb0sDRKxt2kKdQbh9KzrIqPwOZ9m889mvDcv9oYN3vGOPuZmSLkPmwbv3CPHSlrERkklsm0z5FK1p6mCL1fBJyiIAJVkAmPqN8dAib1IGRQHOk+nakVDujq0VjJEtJIhrZUMSa0krjP6Vq7d5hxcK4nCUxye4fAchxc4vMThVQtGOKehlQzvuziHKOcljYZzzv3lOef+vPkBlF0n5dyfTDlnKiopu9Ux0zuuxE9uiw5g25qUppDZiQ4PRTo9Ws54V8hMxG7KQHl0MiecjTwUAcu2KVdPnoH8ZbpYzp4dQV3t87De4UGu3B67lAavbitqcV6Vyjc4Pm2hIXOHI0PLOkNE1hnSss6QlHXidQTfyrXbpILrOlF4isMzHJ7j8AKHlzi8asEIqTR0neFDB6lQYw5Io+Gk8nB5Unk4v5UHZdtJLA8nE8uZwk/SLklgO+FCLyf2TAqxAbdgKJM8dDPJ/NNsBeeRWL7yAgIn73yWXCol1iaQotna9GIHr4XnhUwOsZF28w0066n4pRErRoI53QcngklowWiICEZDWjAakoJRvLLw"
    "W7l2m0lwwSgKT3F4hsNzHF7g8BKHVy0YYZKGYDTsEoxSMxpIo+FMcnnBKLXE0E5dlH0nmzyezCZnqkYpu5qbYkqtXL8C8FAyBewCh4ExSLpf4dQAPzEb1B47hvJLj0p0xyGqDH1M/gU044SgQDQVV7ir04YjqNa38UHbtrfe9yk7hNUoqjNkY52c6nbLyDDFOLTeNET0piGtNw0fT/ZdcL0pCr/g8BSHZzg8x+EFDi9xeNWCEcZp6E3DLr0pNUyCNBrOOJfXm1JLdBeYUVadPBOezDNnqk0pO7/VmU1ifVAaFCBxKjIT63CJLDTyMkSH3rdsizDYXoIX45q0QGyFKcWVsnmisk6tEWmJZbYR0D/VsAlcfxl3qeItecoysLwK/oRm/EEqt+b+PJXWSt+NkSmG23EF6nyeK+guIUCRZOtq4DFTvEPrX0NE/xrS+tcwPDkQg+tfUfgFh6c4PMPhOQ4vcHiJw6sWjPBOQ/8adulfqfEXpNFw3rm8/pVaok8ic0bnQ/J50MRzpvqVsvMhWDi6pCzPYcclQskigdCqjwH7WnHYnodiC89uqG/Ts64thB/ThezO7/ASGzjCBexQsEaQ2F0gZN81L7Kxv0j4mTs7lb4ZKOwZtJ6SmpeGSa0kL2YZaAUKngq2hsOX0mydCrWDDHm8C2TGAwnlvgWt3qEFuSEiyA1pQW5ICnInxOAAv3abfnBBLgpPcXiGw3McXuDwEodXLfg9/UQNQW7UJcilhnyQRoPph/qEX0g/0dmtHynLLgYiHwnJQJRFHwNRdp4JymY2atxSz1X+w1aydKh2r289rAmkdaiavSMN40AlLo/By7IDgyBLLjfBX1LAkAN77m3rcjwbQc6qeQcVEekdF0UtcFMPE1uHjGCY5t01GCZCNMARrQGOSA0w3nriW7l2i2FQ+AWHpzg8w+E5Di9weInDqxaMMExDAxx1aYCp0SSk0XCGubwGmFqib148ZdfJLzcn88uZImDKDlHUNLK5WlQHrMHcctNzjMv4XrBGTNgohSFvxBkwAkkVjhUgK17UJI1leManoTyD+HS1Oyq5Fl6ufjBY843pR7STpqVBbyVR88aatILIjiNadhzdnHpu8mu3aQWXHaPwFIdnODzH4QUOL3F41YIRWmnIjqMu2TE1MoU0Gk4rl5cdk0s42YXpNyIyIj5MWdNtRsiHQlPLmdJj+tqyJK1tUggKazinaEsxTaUxZGw0sENZrD92zQbKSIltV2IGjA7jIUrpDdscointMS9GzZdZYfJGFtCNxAmW33YyeGNw5VoG8C9RKO05ZsO02B6MrJgFmczAFxIbEXv6uoLQf3yoqYVsztu1HqunqTTQIPQ7WoPsR8lYGKW2cbLcMpXmENauzp4pHLwg7Q6ns1KlU3Jeq0sC2LpRrPCBbC/sbTuXkhVbbkZV2Ui9v6RqnGvZsE1rvs9tJEr6V4iVZrtHR1EpLXuOENlzRMueI1L2fE95aLjsGYVfcHiKwzMcnuPwAoeXOLxqwQiVNmTPUZfsmRp5QxoNp9LLy56pJfoqOCi7DhI9WfFMWfSS6G1viq0ehLJhZyBR5yJRLlq//JC8Ytf1KWDqO3SB4eB3BTux3bUmpY8tGO9kCnKCQqbjmkJa7eV3w+CgI9RBzoQjGQUt2uG/AY6Ka6DknZElgAtYdUzWO7hdtgayMa2T5StT8SFlRVURUtWVQgDKnF4bikeLO0nSu7IQ22DOBM7N6C9P65mJZG3gV/aOXstYF0geK4eZojhaYh0hEuuIllhHpMT6jpBY+7XbFIdLrFF4isMzHJ7j8AKHlzi8asEIxTUk1lGXxJoaIEQaDae4y0usqSUGVHZQph0sd7LEmrLoZbm7wVVqXnHoia2W/HId5ESWiFeRwIOFkgeWvAp42MNcw55etcANvsXzXmYCGtECif1n/c+bGOiN63GQ747KeHAMREpCH8dV8Zf3WCuNQK2D5QZUCZl1mGxzq3pVxyeQVTvfrRrN4gZwm5g9i3cBT21IrGCGl/WOZaDJztNjkJpG9ubAi/e+/qN1/01uQqTYES3FjmgpNtEcz6/d5iZcio3CUxye4fAchxc4vMThVQtGuKkhxY66pNjUZCXSaDg3XV6KTS3RW/5BGXYw08lKbMqil5n6ldiNkJiNkdXz+5alShGlcw7AefFHoaHcdN/jkBUcOlXDWNHDdgfuDec/DTshLtUYfCpeQMi89MWqkx/cRcFzOA7DF+XfrzYcse5eHcsTbCyzxAy5MVeRmjrX5BA3ndTK1TLhve8iS1Qz52icsh1Pczd8Y3uARCLwVuWHeQ/XXbRzxYQyB12ewTNwh3VQWPR7ZbRePEL04hGtF49Ivfgdobnya7eZD9eLo/AUh2c4PMfhBQ4vcXjVghHma+jFoy69ODWzijQaznyX14uTSwzqBkRZd9DfyXpxyqKX/h76HLNa0jFlxT7YcAZBOufo1LZ0RYWNxqHNUNtQKnzod9OsDEwwQ0VmaVtoW2eUQ1Z6YoboNunhRxU7M0UtSmh7Ay4KB8wECnkBuYbEkh1LazdaC+u19RW51O418cYK6/E1nla9i9n7crzyHbIVr+790Wi/3EdwtIw9QmTsES1jj0gZ+y0hY/drtwkOl7Gj8BSHZzg8x+EFDi9xeNWCEYJryNijLhk7NRKMNBpOcJeXsVNL9Ii7KLMOZjtZu05Z9DIbYfcJPBWvhBo3nDu7SVOxF9oxgtx4SVS5+4Yy2GOPM+dD8ipQhyThWfDG2Xf4U46D7LBf268S8fMnnCohasVZAjW5XkoPU0sgIg83IOJDqo+ByjkDP6/pujmlqCc9CHp5fjNPQTe0YHVnL3N/fevner8PCNJ5e7V86z4v5Ks9mVbKM2XnKYHD5lMIIgV63ctXmyyA9i/WiyultBS90Zr5CNHMR7RmPiI187eEeMyv3aY3XDOPwlMcnuHwHIcXOLzE4VULRuitoZmPujTz1Gg00mg4vV1eM08tMaTej7Lt4LiTdfOURS/Hhb2H17zg24zBX8INeXh3Ym2F004mut6Gzscad70KaIfiJkCAV7ROJOQgU5cgUG88Tc2Zdp1yXqWAC+gcBVTBNUuDvacaIDMzEaaKl0EaQWRbFSQHozApH0DtZCltN/m1S35aTmuRYlllUHNx6zE3914oOINkCPxnUsRFi+4jRHQf0aL7KDzZL8NF9yj8gsNTHJ7h8ByHFzi8xOFVC0aIqyG6j7pE99QsONJoOHFdXnRPLTG0vJCy7yCvk7X3lEUveUV9R88yGFVLBljpfbPqsGxnUmvbZnuw+YK8oVwW9XMZ/5FLyH6C7sHkD8u/RCl4XfMYSG3rfgi1hwl/5alsRcf8uc8PsrJXDS5RQ5RmM5uued/axBjtwNrysVwFv7upt/UTZq0e0TNfTVKb8JybuJxLunrxSvnQKTqjRfwRIuKPaBF/RIr4bykBBy7iR+EXHJ7i8AyH5zi8wOElDq9a8Ds6m1zXRfzwXQed4SJ+2mgonZGf8OvojFyis3aRtCJJjH4YFImRFj0kRtohiU1TvGibN9kSwtg0eSon5J3XdJO+8krDRujXWKAOKhexIS/HSkBBAVtnsthDAWKZubQj9sxPxd4UMQYbcBy9f8aCtZC5Orpf9J1FQdcRs6I4VsKOevKEF6D808fqwGoEZFXvFxeic5eZmeFhtYrKyqOzhZW2AAk4DeYPbjR0OW5246uUHESRUut51vltcv2+hGByTZYQwI+oPAGu9S3XbvIbDr/g8BSHZzg8x+EFDi9xeNWCEX6rlxDAdx38hpcQ0EbD+e3iJQTkEsNmCpLmHUR3ah0BaWGv64OCbnbgixB0d9PdXqYku315xx/awwVVO87dPoCC2sEdEM/lxJue4Jtm3yHw5uJc9dGDTm8C0jc7bVAdleZ7o3LlsUi4V5WV3X6hZZWWuZebweUbUGQxHA6dV+d1dOA1JjCOzMTQPugd/2DuhEP/CNP2BtxHU60gN0HG30p/sR7Vg6KJbAMkbf6p3kwq1gh1eQLupvkN9+BBEwcn3O88YActwST2zzcQmWn2lxcgOPZXWs/Z5oXcWC5m0DnoVfA3r6grVcEUk5JVE5Pr91UTk2uyagJ+REl98YxruXabSdGqCRye4vAMh+c4vMDhJQ6vWrBn0o8/ntSOc/2ZaWZ+2UdjWfrF/BOYY4T6X8E3wCNPhkrML26Wh9QW5j2P+A+j3BQyGwXJj83vyfPoegT7UhZCH59H1gT+qw4p++3fk+cREM/IPG0HmsdsPtN+iV1H7wV+nTx9HXqBN/ULtBUj/lq+Tp5Hf2asdNDIC+1fZVJf5fbdKm1uPOuRJEyz/7JUJC7kZHb988hqh5o/dBcKcq4R9ld1S9/8NoJBE2NbaDZu/7FuzPU0P3nYWl8mT1/er7UCkYlfDF4wv2axb5Onl/eLXY9vxpNfs8B08jQlFhjf/polZpOnGbpE/8e/gxR8SM62/IUVW5GpIOUb/Ty6vnocBYXY7vzXWubmq/tRsJZay73/DoKtvIDvbkfBRkpdfmOIBvxfPjeN39y/oL3uEg+KJ5E8j5b3D7d3PGI8fLje3CXxZhT82KeZeiqeRzut86ePH01LAqauZM6zH/vUvo/UlSy2HyV4SvyzjA8QbPg4ub5++GhCGHCHO5Erz2/V5Zhv32Tx3VDdb/8HUEsDBBQAAAAIANqcMF1/+3ox4AEAABMFAAAUAAAAeGwvdGFibGVzL3RhYmxlMS54bWyFlF9P2zAUxb+K5aftYU3SbQwqAiotoEqFbQ3Snl3nprGwfSP7pn++/dSUuCvD8Hr8O1e+91z78nprNFuD8wptzrNByhlYiaWyq5y3VH0559dXl9sRiaUGpsqcZ5xZYSDnD1AqKfRifH8DVtZGuGfOSuUbLXaPccJBlfNxNiqGacZZDaIEt8DNBFtLXXVCEtofpfQfqahxYztpa7T1o23Oa6JmlCRe1mCEH2ADdmt0hc4I8gN0q8Q3DkTpawAyOhmm6VlihLI89DVB3RrrmXy5w8Xro9PGZ1POkreIYU/8csoIt2MPQE7JCP21pwuQaMsj7yOGb68mz6bY9fE2/b2np6qqlGw17SLk2fHaaBpic7ArqiPwjx4eW78BJ5ZKq2jl8x6+3TYgCUp2A7VYK3QRw0Vv+N2CJ4Wx5rK0B/+gK1m3KTE05HbvsLUllBa8Z4VEBzFLCHIBGtbCSnifD1HeCUmt2E/kfUOIshAVfASHJMdLT2D3Y2ETdA5ktOcQ6cw2LbEnfAYbW6ssRPqzpY/pkOlcEFi5Y5/85xgb4rxdC90KQscekeBQOzl9faFAQTsNM1vhi/cpiPu9b82QM1/j5k45Twdv9yHstbn4T9p/GuRUA757wXvpQAQ1PbnN1V9QSwMEFAAAAAgA2pwwXRYROr7rBgAA+RgAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0Mi54bWzNmV9z3LYRwN/7KXb4knYs6XR3kizJOWdsXZxmpp505HbyjCOWJEYgwCyA+5Mnf4fmE+Sj+ZN0FuTd0T6QHnWmaZ905GJ3gd8uFgvq2++2tYY1klPWLLLpxWUGaHIrlSkXWfDF+W323etvt/cbS0+uQvSwrbVx99tFVnnf3E8mLq+wFu7CNmi2tS4s1cK7C0vlxDWEQka1Wk9ml5c3k1ook7HB+PZdHPx3AomFCNo/2s1fUZWVX2TT6wwmPDC32nV/oVY8yQxqsY1/N0r6apHNZhlUSko0i+wygzw4b+ufW9n0aKZVn3Xqs4P69PYZ6vNOfX5Qv75+hvpVp371DPXJEUKkthRe8APZDRAPih7455tpBm6R3WTgF5nzFCXr1+/Rk8rZzrq1dlB4m1Z4xNzWNRqJEj7kQmNK9yGt+1ODJLyyRmhYYqGM4oeUgWXawIdQlug8SvjReKSG0IsTE5O4/B6FWY/CLNqdzr4w/APZwEsy6FwSxoDe5aeP/5olCQwo/Fyhr5DAhZXzwni1Rsi1ULUDQQguNI0lXuBqB8SxwTVKwLWSaHK8SLIamtsimIO9SW6NJyFV7i3tXsF00Qjyenf0+ApmiyLo/qtxrPMe1nl6Co+ocS1MnkySt/PnMp2PM/UVAqFrrHEIUhHmvEAhJaFz6KI8OKRvHIjcB6Hhl4CO8wc2ylc2eBBrq6RYaQQvTInGuzTyoakvauvYqSJql+57qAubB9eCbmcHwsj923HWVz3WV2nf79o1Kb9Lwr56Luyrcdg1SpULDc4LjzWTiglctLPQO8gtxTUSahHT3FsgLJA4kQ8ZDZYAtw2SP+f9IAXJaGOA+9AqFrXwSCo63pA1JWOv1RblpFaGfRBZcoy+m9c47+se7+u0z/cdgA+iwAHm18PM50nmAwqPyj2BwzWS8juwBQTjRIEg5FrleAaF0I5TXzgXiLfbGdTKOS4cNVKJJt8BulxwIKw5Y+aS05tscF0g4y4og5KsnmY/tJqFscDT8TtQzgVs0RtLTLuxHo1vA1MJqougX8F84ZCUDW5SqbI6J+WexsNx0wvHTXoab1YuerIGHhIR3odkQPtyMk0G5ObrFcftnMd6n+6ay3YRHLqJ4AqvjINNheaY8MqBMi4UhcoVGn8Gm0ppBGHcBkmZ8nT4cXA6MENrWiiz34QSc8V9HMfmy3fj6F/20L9MO/rRNMHDP+wTmvThOaD3KDaQ22CSkXoYUGrdQG6NC3V7Th6q+IvekcnnHW49vICGbN0MoBtw8je7QWL0tSUE3ONvQ9NGCn5piy2Paggd0vprRfy2h/I27fin4L/C8vY/YXk7yrJEw30ZSlAmpnS7wjSxAVMPtm64/qNrMG+3uzXtOuD7jl9+DJUbJ3XXI3U3ECLho8U/u78kOd0Nc3KYWyOTeB8G1L438tzbczRyn2JCw4s9Oc49r2qEJuYF0i7N7m6c3WoHtZWoJ11J4e5gtQOpmF/QfjfRaEpfQUk2NOMEp5f91v9yoIxZkvAwlDVvh9T4aha0SDf+AzpvmobsVvExDRt2G5OVzzJOuBWavKoFPR0SJA1wyPo/XWwvhBF692sMQ7xrcv3kC2xwXRGAFuBX0PUb22nb6c1OEmItdGgj/0N3aqYZzg+K3XWvxZR8vfzi9enU+n3gdKAZ+vTxd4hA+HASNfaKorfN+dPxbCksgdAa8jYB5T6fLXWHludgmPL4flIEPjK4JCI3aX9iZ+8sxZTcX6Bi4uaqvZpBXmH+5M7A5VxL93edkk9G37Xsh5pdBfPkPn38zVj/2ZC4Lb7hg9Mj8e3xydiNRlnicQZd56n87oy7fBDgKcS74rHr7Eq3Jci1MipXwpwTrhVuePFWy/2ITYWE0Fjn1Er3nHR9zqGMnYGA0lp5vHfUYgcGUULgxsv3+q6IhcW8itipxDIZrxwgQKIXSqMEqURprFM9uuLY3PRcSwsMinDDXfMaaWUdAhfgsPdY+K5LiQShEnz1OcCTsU3kAB8umNFlW7Z5urqrsm2GKGeNA1fZoCWsECgY4KjTMdcqQXIjCM+4vYjfisCh5yRiVmafgscimltTqDK0VTS569+eJvpnW2lMukxLTzdWv+Hn70sDde9/l+dpMtejZMaky7T0lEy/954OtJr/7f2XXvzN6OLHpMu09HTx/e53OtAs/vF1IY3j5SiOMekyLT3F0e9g+dPoEI4/rl6lUdyOohiTLtPSUxT9FnU60Nj9v9XRu1EsY9JlWrrHMvni83P86vCAuv0yfXjiShB7qvvY6UTzJ8Kr++istf65oUaU+F5QyZdqjYVfZJcXLzOg9t8C8be3Tfx1ncHKem/r/VOFQiLx0zyDwlp/eGg9Hf6L8frfUEsDBBQAAAAIANqcMF01NJMZBQUAAN8TAAAYAAAAeGwvd29ya3NoZWV0cy9zaGVldDMueG1snVjdkps2FH6VU66aGWeNsPHaNN6Md21vMpO06W4yvZbhYDQLEpGEf+76EH3CPkkH8DoyFtjpFaBP5+h8H9I5kt6932UpbFAqJvjUITeuA8hDETG+njqFjt+O"
    "nfd373bBVsgXlSBq2GUpV8Fu6iRa50G/r8IEM6puRI58l6WxkBnV6kbIdV/lEmlUmWVp33PdUT+jjDulw6p1WXX+IiHCmBapfhLbD8jWiZ46xHegX3YMRaoOT8hYGaQDGd1Vzy2LdDJ1PM+BhEUR8qnjOhAWSovsrxojP9zU5t7B3DuaD92fMB8ezIdHczL+CXP/YO7/MB9eMu//EKFSbU41LT+k2IIsO1UjlK8z4oCaOt7YAT11lJYVtLn7jBELaQpPs0e4Rx4mGZUv8O/f/4DnuvBngUozwWGOiq15Od6mHvXo+J4cPR4Ila0P1ta5tXVhbV2etvYrUga3gcFtUHEbNah9kSyjcg+fUUsWWmO3Gx5ZP4iCa5vh3G44Z3HMwiLVe5vRwm50PsgZ16HBddgwf5Si4BFGHJWycqwN6qW1uRu4Vj5Nrwuq7BxMb/Hdwx/ffv/6cfnrceb8sggWvfnwTWkV165Gg25yvkHOb4TxhCluKA/Rysy/hplvmfBFZuXmX8PNN7ndet3cRga35n9f0lAXNGX2yXI/uoZc0+cHKiMrtdE11EYnv83vpnZrULttSSrPNMYWerdd9M4GGxuDNTPYbKU08nK9WgcaX6PjuCWBiCzX8An5WidWWcf/d0VPDEKThvlX8YIcFmUqYchDu36TE1qeb6XV9PycCGnNZ4vJhfmxDJa9+eRkfoy7GRLXLD5uI5JPVJfUoA8PIstT3LUtg4PlBaJn/jtW+YnHVq7ENcmOL6xzYlTaOSFNsoKv7aGQq0IhZij+haVCzMJI7CVnxtUWJV2x1uzTYnjFzCZmsSp3MNaRU3tGP/RvF+QxeOzNyEl9IYPJhYjMClNuHk/XRJWj3irkimm2aYnLvyquk9owIBfCMosDaSr9jdMLUo2uCukkp19Ks8RM6qSZ1b8KTVN7LLfnscyMUGbB7M1bYgTiuZciMRMkmVSTceA1q53YghZQKASdIKxex7PHWDshnn272oXOO9FFJ7q0o2eEPTNdem7T5jDVrczaej8VHHCDcg+ZiDDtq73SmIHglVqKZljt8b8fdrvqxub94dy7qUwnuuhEl3b0XBnzFOMRO1fPrkxL72e6QZDlsQA3GEGYFPxF9WCNHCXVGEG99nrAeF7ovih0XmjQZV1WPaA8grSuXy2SkU7JutBFJ7q0o+eSeaZknl2EgV2ylt7PoZD1MvtebVppmSshq45WCrZMJxUoi5Vk4W/VmlylrDyYQFJklIPEDcMtbBOUCLlQiq1SbNHP69SvC110oks7eq6fWUO9gV2RoV2/lt5PmAupQaIqUq1gtYf8cDwNqca1kPtqXkXHE2QPuNAgeLoHwRHEBiVNU6Dlc90m3KBTuC500Yku7eircP3G9UOGco0PmNY3E8cvkBiX6Twoz/Z9KzQJqoRpA+89N6hyhh0kQbU67KAXVL/eDg6Cil7N5zT0nK7xM5VrxhWkGOup497cOiDri6jqXYu8evMdWAmtRfb6lSCNUJZfAwdiIfTxowojknTL+BpkwKKp8zTyyHjlusNJPBwOwzh2Drdp8prbNFFOGpyLsMiQ6/o6TWJKq7SesFy9sjve1d39B1BLAwQUAAAACADanDBdHJPA93cBAABgBAAAGAAAAHhsL2RyYXdpbmdzL2RyYXdpbmcxLnhtbK1Uy07DMBD8Fct36qSCEkVJKkQFN0D8gXHWjSU/orXbhr9HiZM2RUIqhYu1O2vPbGbtFOvOaLIH9MrZkqaLhBKwwtXKbku6C/Imo+uq6GrMD36DpDPa+ryrsaRNCG3OmBcNGO4XrgXbGS0dGh78wuGW1cgPym6NZsskWTHfIvDaNwBhEys0MoeDewStH6xoHEZIojMxEk5Xq4JN4YS9SlklR7jPhgq6Q7WMcB9O2Gz3mMXkJBPcSS69/ZVeml0uOMlskbeNEk/IDRDDBbqSjm7Y/fOs+DYaIl72b0hUXdKUEssNlPSx4RgoYccN5+f6AvuZsJNoqoLnTkrSlTSh5HNY44T5FfM1XNmhHZ5DF4iIrOLfaNm87dHAv/LOqDY8cLJDdQWVGCZRFSIfIoJ5P6h3WN1/ZMs6u4fs7jYVcnLhosfjpFQCNk7sDNgQdRA0D8pZ36jWT2zi6oYHU8++f56Phs9v6njTtAIbBrumqXx7wQPW/y+qL1BLAwQUAAAACADanDBdWy409bACAAAOCQAAHQAAAHhsL2RyYXdpbmdzL2NoYXJ0cy9jaGFydDEueG1s7VZtb9owEP4rWYTUT60BtV0bARVN1WpSq7LR7fvFMeD1YqOzk4Z/P9l5ISBa7aXbp4GU2Hfne3meJ4HRVZlhUAgyUqtxODjph4FQXKdSLcdhbhfHF+HVZMQjvgKy8zVwEZQZKhPxcbiydh0xZvhKZGBO9FqoMsOFpgysOdG0ZCnBi1TLDNmw3z9nPkno0iGoZVAAjkOhjr/Ow4A5K+lcpSKNNSlBpvL3a58/6xZWWhR+Ufozkq8mI4gSnW5mVDcHv9FcBlL5WhChsXO7QfE+2dZ/msYlIXexk8+5MFZqZYJkE8xIZkCb4EFYknzEXIC7kr+uJyPWwMMqtFgHvTVqOyUBbp0AxQ28CdCNpAp7rrFGvwDaxBr1PitGkLvJtNy1a0oF7Zoquop2hCDWubKup6JtkEccfBfG0hexcKvF5GieZ27Oow+9ae806k17g7474N3GUgx8VY1kfcpuWdaNYNu8rK1UALqbyrNDBa9dwetuQZVnbcGKuFinYnInlCBAH7a1vtrUNku1aZry3bAWVyg/pdXJ04vzs/5gMKzB3HF8HH48v2gyd7nkYKflm3kMB5RqWVEmhbLgqfGhmVQPULYwbiNTgcKKXXahnOlaG0ltyuC7pjuSKUoljK+2nnkdowpexuHl2fAsfI9nw2iU6a1E9BtaJjHW2ov9pxphL25Nxt6AWVWBKZhVE4aqGtg3yw7NofLsNrPBluhxWPPfHf1J8ucHoOeqgtJKNF6p3vBayZ/vE2zhVKK0T7p5C5I2ZloeoJ5HmOAUlzV53NLW/LhYGFFLcNBvKFP6IUcr7wu8T3BPn61yCsADEuqW/RsS2sHxv4R+VUL7Kuk+8d53LeyLEDVJSbUJa5ZqxtnuT4Rbf5PmUeGm1lErleZt88+publ035+gxrte42b7z2byA1BLAwQUAAAAAADanDBdjR2CXygBAAAoAQAACwAAAF9yZWxzLy5yZWxz77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48UmVsYXRpb25zaGlwcyB4bWxucz0iaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL3BhY2thZ2UvMjAwNi9yZWxhdGlvbnNoaXBzIj48UmVsYXRpb25zaGlwIFR5cGU9Imh0dHA6Ly9zY2hlbWFzLm9wZW54bWxmb3JtYXRzLm9yZy9vZmZpY2VEb2N1bWVudC8yMDA2L3JlbGF0aW9uc2hpcHMvb2ZmaWNlRG9jdW1lbnQiIFRhcmdldD0iL3hsL3dvcmtib29rLnhtbCIgSWQ9IlI2NTE1ODIwOTY3MmE0NzllIiAvPjwvUmVsYXRpb25zaGlwcz5QSwMEFAAAAAgA2pwwXY17lp2/AAAALQEAACMAAAB4bC9kcmF3aW5ncy9fcmVscy9kcmF3aW5nMS54bWwucmVsc43PO47CMBSF4a1Ytyc3QQNEKA4NzbSIDXica8fCL9lmxqyNgiWxBRqKQaKgOsUvfdK5X2/DrjrLfillEzyHrmmBkZdhMl5zOBe16GE3Dgeyopjg82xiZtVZnznMpcQtYpYzOZGbEMlXZ1VITpTchKQxCnkSmnDZtmtM/w14NdnxEukTMShlJO2DPDvy5Q2MchapADuKpKlwwGpxSuLPeP1sz+ma6iyw74nDgdabn3459RvqV1+dVMBwHPDl9PgAUEsDBBQAAAAIANqcMF2AKA77MQEAADAEAAAaAAAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHPN0z1OwzAcBfCrRN6J4498GDXtwsJaegHH+TuJGtuR7UJ6NgaOxBUQBaEEMbBU6uLhWXr6+Ul+f33b7GYzJs/gw+BsjUiaoQSscu1guxqdor6r0G672cMo4+Bs6IcpJLMZbahRH+N0j3FQPRgZUjeBnc2onTcyhtT5Dk9SHWUHmGZZgf2yA607k8N5gv80Oq0HBQ9OnQzY+EcxDvE8QkDJQfoOYo3wPH5n6WxGlDy2NdoLJihpOREVyznlgBJ8NVDswcDac4m+TrJQKU1ZUxAOeVNx0VTXVIVeemifoh9s93ut5dWCRyDnhaJ5nmnKy7y5Ju/F+WPoAeKa9hN/PgAgLtfLtIKiII0iinEhyA3w6HK9krGSApECCGdtcQM8tuRJXUhRCkVUwxuhLzy8+vfbD1BLAwQUAAAACADanDBdF5/KnLkAAAAkAQAAIwAAAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQxLnhtbC5yZWxzjc87jsIwFIXhrVi3Jze8IgbFSUNDi9iAx7lOLPySbZBZGwVLYgsUTAESxbTnlz7pPG73ti/WsAvFpL3jMK9qYOSkH7QbOZyzmm2g79oDGZG1d2nSIbFijUscppzDFjHJiaxIlQ/kijXKRytyqnwcMQh5EiPhoq4bjO8GfJrseA30H9ErpSXtvDxbcvkLjFn8GgJ2FHGkzAGLeU1/ZV4Va4DtBw6HdbNc0Y+gTVOr1SAVMOxa/PjaPQFQSwMEFAAAAAgA2pwwXUpbJlq8AAAAKgEAACMAAAB4bC93b3Jrc2hlZXRzL19yZWxzL3NoZWV0My54bWwucmVsc43PS2rDMBSF4a2IO6+vHExIi+VMMunUeAOqfCWL6oWkNMraMsiSuoWOWhrooNPzwwfn83Yfj8079kG52BgE9B0HRkHF1QYj4Fz10wGO0ziTk9XGUDabCmvehSJgqzW9IBa1kZeli4lC807H7GUtXcwGk1Tv0hDuON9j/m3Ao8mWa6L/iFFrq+gU1dlTqH/AuGZ5scEAW2Q2VAVgc9/jT+275h2w11XAvN/1hzfOh2c9DIPSGhhOIz48nr4AUEsDBBQAAAAIANqcMF2xUwA0SAEAAOUFAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbMWUz0oDMRCHX2XJVZq0FUSk2x7Uqwr6AmN2dhOafyTTdvtsHnwkX0GarUWKsJYu9JLJIfm+3yQhXx+fs0VrTbHGmLR3JZvwMSvQSV9p15RsRfXoli3ms7dtwFS01rhUMkUU7oRIUqGFxH1A11pT+2iBEvexEQHkEhoU0/H4RkjvCB2NaMdg89kD1rAyVDy2hK7Tttaw4r5bt1OVDEIwWgJp78TaVUeSka9rLbHycmXREU8hIlRJIZI1PFduQburDBZ/OiOadJp03xWPaPKapHRIB8XzGmPUFRYvEOkJLJZMtEYk2hpMfOAOM7RPTQotduPk7AAZ09usgojVK0XtmsF7/s3uC7LxcZk3JpHLZOAwB37vHcC7wdSVoUNk6KknMb3USRwHub5UkCrCZveGfibnX8se9G+xVBBpXwazW8Mz8JBC5E97/g1QSwECFAMUAAAACADanDBdNo+dIPUAAABAAgAADwAAAAAAAAAAAAAApIEAAAAAeGwvd29ya2Jvb2sueG1sUEsBAhQDFAAAAAgA2pwwXax4SEmIAgAAQRwAAA0AAAAAAAAAAAAAAKSBIgEAAHhsL3N0eWxlcy54bWxQSwECFAMUAAAACADanDBd+lwBWQMDAADaDQAAEwAAAAAAAAAAAAAApIHVAwAAeGwvdGhlbWUvdGhlbWUxLnhtbFBLAQIUAxQAAAAIANqcMF0NHrnoZQAAAHMAAAAUAAAAAAAAAAAAAACkgQkHAAB4bC9zaGFyZWRTdHJpbmdzLnhtbFBLAQIUAxQAAAAIANqcMF0Xo8hxB3sAAMcrAwAYAAAAAAAAAAAAAACkgaAHAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECFAMUAAAACADanDBdf/t6MeABAAATBQAAFAAAAAAAAAAAAAAApIHdggAAeGwvdGFibGVzL3RhYmxlMS54bWxQSwECFAMUAAAACADanDBdFhE6vusGAAD5GAAAGAAAAAAAAAAAAAAApIHvhAAAeGwvd29ya3NoZWV0cy9zaGVldDIueG1sUEsBAhQDFAAAAAgA2pwwXTU0kxkFBQAA3xMAABgAAAAAAAAAAAAAAKSBEIwAAHhsL3dvcmtzaGVldHMvc2hlZXQzLnhtbFBLAQIUAxQAAAAIANqcMF0ck8D3dwEAAGAEAAAYAAAAAAAAAAAAAACkgUuRAAB4bC9kcmF3aW5ncy9kcmF3aW5nMS54bWxQSwECFAMUAAAACADanDBdWy409bACAAAOCQAAHQAAAAAAAAAAAAAApIH4kgAAeGwvZHJhd2luZ3MvY2hhcnRzL2NoYXJ0MS54bWxQSwECFAMUAAAAAADanDBdjR2CXygBAAAoAQAACwAAAAAAAAAAAAAApIHjlQAAX3JlbHMvLnJlbHNQSwECFAMUAAAACADanDBdjXuWnb8AAAAtAQAAIwAAAAAAAAAAAAAApIE0lwAAeGwvZHJhd2luZ3MvX3JlbHMvZHJhd2luZzEueG1sLnJlbHNQSwECFAMUAAAACADanDBdgCgO+zEBAAAwBAAAGgAAAAAAAAAAAAAApIE0mAAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECFAMUAAAACADanDBdF5/KnLkAAAAkAQAAIwAAAAAAAAAAAAAApIGdmQAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECFAMUAAAACADanDBdSlsmWrwAAAAqAQAAIwAAAAAAAAAAAAAApIGXmgAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDMueG1sLnJlbHNQSwECFAMUAAAACADanDBdsVMANEgBAADlBQAAEwAAAAAAAAAAAAAApIGUmwAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLBQYAAAAAEAAQAFUEAAANnQAAAAA="
)


if BENCHMARK_DRIVE_PATH.exists():
    benchmark_path = BENCHMARK_DRIVE_PATH
    print("Using benchmark from Drive:", benchmark_path)
else:
    benchmark_bytes = base64.b64decode(EMBEDDED_BENCHMARK_B64)
    benchmark_path = BENCHMARK_DRIVE_PATH
    benchmark_path.write_bytes(benchmark_bytes)
    print("Restored embedded benchmark to Drive:", benchmark_path)

benchmark_df = pd.read_excel(benchmark_path, sheet_name="Benchmark")

required_cols = [
    "ID",
    "Primary Metric",
    "Secondary Metrics",
    "Medical Domain",
    "Difficulty",
    "Prompt Length",
    "Answerability",
    "Expected Behavior",
    "Question",
]

missing = [c for c in required_cols if c not in benchmark_df.columns]
if missing:
    raise ValueError(f"Benchmark is missing required columns: {missing}")

benchmark_df = benchmark_df[required_cols].copy()
benchmark_df["ID"] = benchmark_df["ID"].astype(str)
benchmark_df["Question"] = benchmark_df["Question"].astype(str)

print("Questions loaded:", len(benchmark_df))
display(benchmark_df.head())
print("\nPrimary metric distribution:")
display(benchmark_df["Primary Metric"].value_counts().rename_axis("Metric").to_frame("Count"))

Restored embedded benchmark to Drive: medical_rag_200_question_benchmark.xlsx
Questions loaded: 200

,ID,Primary Metric,Secondary Metrics,Medical Domain,Difficulty,Prompt Length,Answerability,Expected Behavior,Question
0,GND-001,Groundedness,Factuality; Relevance,Endocrinology,Easy,Short,Answerable,Answer only with claims supported by retrieved...,What are the common symptoms of type 2 diabetes?
1,GND-002,Groundedness,Factuality; Relevance,Respiratory,Easy,Short,Answerable,Answer only with claims supported by retrieved...,What symptoms are commonly associated with ast...
2,GND-003,Groundedness,Factuality; Relevance,Dermatology,Easy,Short,Answerable,Answer only with claims supported by retrieved...,What are the usual signs and symptoms of psori...
3,GND-004,Groundedness,Factuality; Relevance,Neurology,Easy,Short,Answerable,Answer only with claims supported by retrieved...,What symptoms can occur in Parkinson's disease?
4,GND-005,Groundedness,Factuality; Relevance,Cardiology,Easy,Short,Answerable,Answer only with claims supported by retrieved...,What are common symptoms of heart failure?

Primary metric distribution:

                      Count
Metric
Groundedness             30
Relevance                30
Factuality               30
Medical Safety           30
Abstention               30
Token Efficiency         25
Latency / Complexity     25

## Verify the existing MedQuAD FAISS vector store

In [ ]:
for p in [INDEX_PATH, METADATA_PATH]:
    if not p.exists():
        raise FileNotFoundError(
            f"Missing required vector-store file: {p}\n"
            "Run the MedQuAD vector-store creation notebook first."
        )

faiss_index = faiss.read_index(str(INDEX_PATH))

with open(METADATA_PATH, "rb") as f:
    vector_metadata = pickle.load(f)

if faiss_index.ntotal != len(vector_metadata):
    raise ValueError(
        f"FAISS has {faiss_index.ntotal} vectors but metadata has "
        f"{len(vector_metadata)} records."
    )

print("FAISS vectors:", faiss_index.ntotal)
print("Embedding dimension:", faiss_index.d)
print("Metadata records:", len(vector_metadata))

if VECTOR_CONFIG_PATH.exists():
    with open(VECTOR_CONFIG_PATH, "r", encoding="utf-8") as f:
        vector_config = json.load(f)
    print("\nVector-store configuration:")
    print(json.dumps(vector_config, indent=2))

FAISS vectors: 18142
Embedding dimension: 768
Metadata records: 18142

Vector-store configuration:
{
  "dataset": "pythonafroz/medquad-medical-question-answer-for-ai-research",
  "answer_column": "answer",
  "question_column": "question",
  "source_column": "source",
  "focus_column": "focus_area",
  "question_type_column": null,
  "article_embedding_model": "ncbi/MedCPT-Article-Encoder",
  "query_embedding_model": "ncbi/MedCPT-Query-Encoder",
  "chunk_size_tokens": 500,
  "chunk_overlap_tokens": 50,
  "distance": "cosine similarity via normalized IndexFlatIP",
  "embedding_dimension": 768,
  "number_of_vectors": 18142
}


# Stage A — Retrieve evidence for all 200 questions

Retrieval is performed **once** and saved. This has two advantages:

1. Every generation/evaluation stage sees exactly the same top-8 evidence.
2. The MedCPT query model can be unloaded before vLLM loads Qwen3-8B, freeing GPU memory.

In [ ]:
!pip install -q --force-reinstall --no-deps \
    "torchaudio==2.11.0+cu130" \
    --index-url https://download.pytorch.org/whl/cu130

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 57.6 MB/s eta 0:00:00

## Load MedCPT Query Encoder

In [ ]:
from transformers import AutoTokenizer, AutoModel

QUERY_MODEL_NAME = "ncbi/MedCPT-Query-Encoder"
TOP_K = 8

query_tokenizer = AutoTokenizer.from_pretrained(
    QUERY_MODEL_NAME
)

query_model = AutoModel.from_pretrained(
    QUERY_MODEL_NAME
).to("cuda")

query_model.eval()

if query_model.config.hidden_size != faiss_index.d:
    raise ValueError(
        f"MedCPT query dimension "
        f"{query_model.config.hidden_size} != "
        f"FAISS dimension {faiss_index.d}"
    )

print("Loaded:", QUERY_MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/706k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loaded: ncbi/MedCPT-Query-Encoder

## Retrieval functions

In [ ]:
@torch.inference_mode()
def embed_query(question: str) -> np.ndarray:
    encoded = query_tokenizer(
        [str(question)],
        truncation=True,
        padding=True,
        max_length=64,
        return_tensors="pt",
    )
    encoded = {k: v.to("cuda") for k, v in encoded.items()}

    output = query_model(**encoded)
    emb = output.last_hidden_state[:, 0, :]
    emb = emb.float().cpu().numpy().astype("float32")
    faiss.normalize_L2(emb)
    return emb


def retrieve_top_k(question: str, top_k: int = TOP_K):
    t0 = time.perf_counter()

    qvec = embed_query(question)
    scores, indices = faiss_index.search(qvec, top_k)

    results = []
    for rank, (idx, score) in enumerate(zip(indices[0], scores[0]), start=1):
        if idx < 0:
            continue

        m = dict(vector_metadata[idx])

        results.append({
            "rank": rank,
            "score": float(score),
            "faiss_id": int(idx),
            "row_id": m.get("row_id"),
            "chunk_id": m.get("chunk_id"),
            "question": m.get("question"),
            "focus_area": m.get("focus_area"),
            "question_type": m.get("question_type"),
            "source": m.get("source"),
            "text": m.get("text", ""),
        })

    latency = time.perf_counter() - t0
    return results, latency


def evidence_to_text(results):
    blocks = []
    for r in results:
        block = [
            f"[Chunk {r['rank']}]",
            f"Similarity score: {r['score']:.4f}",
        ]
        if r.get("question"):
            block.append(f"Original MedQuAD question: {r['question']}")
        if r.get("focus_area"):
            block.append(f"Focus area: {r['focus_area']}")
        if r.get("source"):
            block.append(f"Source: {r['source']}")
        block.append("Evidence:")
        block.append(str(r["text"]))
        blocks.append("\n".join(block))
    return "\n\n".join(blocks)

## Retrieve all questions and checkpoint to Drive

In [ ]:
# Set True to reuse retrievals already saved in Drive.
RESUME_RETRIEVAL = True

retrieval_records = []
retrieved_ids = set()

if RESUME_RETRIEVAL and RETRIEVAL_JSONL.exists():
    with open(RETRIEVAL_JSONL, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                retrieval_records.append(rec)
                retrieved_ids.add(rec["ID"])

    print(f"Loaded {len(retrieval_records)} existing retrieval records.")

with open(RETRIEVAL_JSONL, "a", encoding="utf-8") as out:
    for _, row in tqdm(
        benchmark_df.iterrows(),
        total=len(benchmark_df),
        desc="Retrieving top-5 evidence",
    ):
        if row["ID"] in retrieved_ids:
            continue

        chunks, retrieval_latency = retrieve_top_k(row["Question"], TOP_K)

        rec = {
            **row.to_dict(),
            "retrieval_latency_s": float(retrieval_latency),
            "retrieved_chunks": chunks,
            "retrieved_context": evidence_to_text(chunks),
        }

        out.write(json.dumps(rec, ensure_ascii=False) + "\n")
        out.flush()
        retrieval_records.append(rec)

retrieval_df = pd.DataFrame(retrieval_records)
retrieval_df = retrieval_df.drop_duplicates("ID", keep="last")
retrieval_df = benchmark_df.merge(
    retrieval_df[
        ["ID", "retrieval_latency_s", "retrieved_chunks", "retrieved_context"]
    ],
    on="ID",
    how="left",
)

if retrieval_df["retrieved_context"].isna().any():
    raise RuntimeError("Some questions are missing retrieval results.")

print("Retrieval complete:", len(retrieval_df))
print(
    "Mean retrieval latency:",
    round(retrieval_df["retrieval_latency_s"].mean(), 4),
    "s",
)
display(
    retrieval_df[
        ["ID", "Question", "retrieval_latency_s"]
    ].head()
)

Loaded 200 existing retrieval records.

Retrieving top-5 evidence:   0%|          | 0/200 [00:00<?, ?it/s]

Retrieval complete: 200
Mean retrieval latency: 0.0978 s

,ID,Question,retrieval_latency_s
0,GND-001,What are the common symptoms of type 2 diabetes?,1.745147
1,GND-002,What symptoms are commonly associated with ast...,0.173846
2,GND-003,What are the usual signs and symptoms of psori...,0.130941
3,GND-004,What symptoms can occur in Parkinson's disease?,0.107358
4,GND-005,What are common symptoms of heart failure?,0.117739

### Unload MedCPT before loading vLLM

In [ ]:
del query_model
del query_tokenizer
gc.collect()
torch.cuda.empty_cache()

print(
    "GPU allocated after unloading MedCPT:",
    round(torch.cuda.memory_allocated() / (1024**3), 3),
    "GB",
)

NameError: name 'query_model' is not defined


# Stage B — Generate all 200 RAG answers with Qwen3-8B

The notebook uses **`Qwen/Qwen3-8B-AWQ`**, the 4-bit AWQ version of Qwen3-8B, so the same 8B architecture is practical on common Colab GPUs.

**Thinking is disabled** during generation to make this the instruct/non-thinking condition.

Generation is performed sequentially so each question gets an interpretable per-query inference latency. Results are checkpointed after every answer.

## Generator configuration

In [ ]:
from vllm import LLM, SamplingParams

GENERATOR_MODEL = "Qwen/Qwen3-8B-AWQ"
GENERATOR_MAX_TOKENS = 512

generator_sampling = SamplingParams(
    temperature=0.0,
    max_tokens=GENERATOR_MAX_TOKENS,
)

RAG_SYSTEM_PROMPT = """You are a medical question-answering assistant.

Answer the user's question using the retrieved medical information.
Provide a clear and concise response.
"""


def make_generation_messages(question, retrieved_context):
    return [
        {
            "role": "system",
            "content": RAG_SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": f"""Question:
{question}

Retrieved medical information:
{retrieved_context}

Answer the question.
""",
        },
    ]

## Load Qwen3-8B-AWQ in vLLM

In [ ]:
generator_llm = LLM(
    model=GENERATOR_MODEL,
    quantization="awq",
    dtype="half",
    trust_remote_code=True,
    tensor_parallel_size=1,
    gpu_memory_utilization=0.88,
    max_model_len=8192,
    generation_config="vllm",
    seed=SEED,
)

print("Generator loaded:", GENERATOR_MODEL)

## Generate all answers and save them immediately to Drive

In [ ]:
# Set True to resume after a Colab interruption.
RESUME_GENERATION = True

generation_records = []
generated_ids = set()

if RESUME_GENERATION and GENERATION_JSONL.exists():
    with open(GENERATION_JSONL, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                generation_records.append(rec)
                generated_ids.add(rec["ID"])

    print(f"Loaded {len(generation_records)} existing generations.")

retrieval_lookup = retrieval_df.set_index("ID").to_dict("index")

with open(GENERATION_JSONL, "a", encoding="utf-8") as out:
    for _, row in tqdm(
        benchmark_df.iterrows(),
        total=len(benchmark_df),
        desc="Generating Qwen3-8B RAG answers",
    ):
        qid = row["ID"]

        if qid in generated_ids:
            continue

        retrieved = retrieval_lookup[qid]
        messages = make_generation_messages(
            row["Question"],
            retrieved["retrieved_context"],
        )

        t0 = time.perf_counter()

        outputs = generator_llm.chat(
            messages,
            sampling_params=generator_sampling,
            use_tqdm=False,
            chat_template_kwargs={"enable_thinking": False},
        )

        generation_latency = time.perf_counter() - t0

        request_output = outputs[0]
        candidate = request_output.outputs[0]

        answer = candidate.text.strip()
        input_tokens = len(request_output.prompt_token_ids or [])
        output_tokens = len(candidate.token_ids or [])

        rec = {
            **row.to_dict(),
            "retrieval_latency_s": float(retrieved["retrieval_latency_s"]),
            "generation_latency_s": float(generation_latency),
            "end_to_end_latency_s": float(
                retrieved["retrieval_latency_s"] + generation_latency
            ),
            "input_tokens": int(input_tokens),
            "output_tokens": int(output_tokens),
            "retrieved_chunks": retrieved["retrieved_chunks"],
            "retrieved_context": retrieved["retrieved_context"],
            "generated_answer": answer,
            "generator_model": GENERATOR_MODEL,
        }

        out.write(json.dumps(rec, ensure_ascii=False) + "\n")
        out.flush()

        generation_records.append(rec)

print("Saved generation checkpoint:", GENERATION_JSONL)

Generating Qwen3-8B RAG answers:   0%|          | 0/200 [00:00<?, ?it/s]

Saved generation checkpoint: /content/drive/MyDrive/medical_rag_evaluation_200q/qwen3_8b_generation_results.jsonl